### ISSUE TITLE
app.element.io very slow in Tangram

### ISSUE THREAD

**Issue by Cogitri** [sonnyp/Tangram#102]
In Tangram app.element.io feels very, very slow (to the point were typing in a letter takes ~1 second), it's especially painful when writing `:` (because that pops open the emoji chooser, which takes 2~5 seconds to open). In Firefox or the Element Electron-App Element is very fast and typing/opening the emoji picker has no noticeable lag. 

**Tangram version**

1.3.1 from Flathub

**Linux distribution**

Fedora Silverblue (but also seen on other distros)

**Flatpak version**

Flatpak 1.8.2

**Desktop environment**

GNOME Shell 3.38a

**Comment by sonnyp** [comment]
Sounds like an issue in WebkitGTK https://github.com/sonnyp/Tangram#reporting-an-issue

**Comment by Cogitri** [comment]
Ah yes, seems like it's also slow in GNOME Web, so this probably is on webkit2gtk
