### ISSUE TITLE
Feature request: Give each web app its own fingerprint

### ISSUE THREAD

**Issue by wepache** [sonnyp/Tangram#112]
::Not sure if I accidentely close the issue earlier. If it was closed by an admin I apologize for reposting::

Firstly, I appreciate the creation of this app. It's a step in the right direction.

I ran a few test and it seems that each web app has the same fingerprint across Tangram. So Google, Facebook or any other type of tracker that has reach across multiple websites will know that it is the same user roaming around different websites.

It would be great if each tab had it's own unique fingerprint so that privacy can be maintained.

**Comment by sonnyp** [comment]
You closed it by accident - see https://github.com/sonnyp/Tangram/issues/111

What method did you use to detect fingerprint ?

**Comment by sonnyp** [comment]
https://github.com/sonnyp/Tangram/issues/111
