### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by lduktus** [sonnyp/Tangram#116]
**Tangram 1.3.1**
**Fedora 33 (Silverblue)**
**Flatpak 1.10.1**
**GNOME Shell 3.38.4 Wayland**

Thank you for the work, I really appreciat this app.
I have several smaller suggestions on imo "missing" features and can open other them in different issues if you prefer that:
1. Add a shortcut to open a new tab.
2. Create Night Mode option:
    While the GTK-Theme can of course be switched some people may like to switch between day/night or may want to force     certain Apps to e.g.: use dark-mode, while they use the lighter variant as default.
3. Add an easy way to copy the current url to clipboard.
4. Maybe add support to define a custom icon, I have some sites which don't provide favicons or where they seem to bug.
    In this case a fallback icon or custom icon would be nice:)
5. Provide a way to export and import sites.

Not really an issue, but just an idea: Maybe there is a good way to provide a list of webapps/-sites that work well with Tangram.
Users could add sites they are using and maybe add a short note if something does not work. This coud users help to discover sites/use-cases.

EDIT: Sorry forgot some points.

**Comment by sonnyp** [comment]
No reason to close this - suggestions are valid.

**Comment by ntnsndr** [comment]
+1 on the import/export! What I would especially love is if there could be a simple config file with a list of sites that could be put in an arbitrary place. My ideal workflow would be to share that file across computers via NextCloud.

Thanks so much for creating this simple, beautiful piece of software.

**Comment by sonnyp** [comment]
> Add a shortcut to open a new tab.

Probably not - it's not a traditional web browser and you're not supposed to do this often.
Why do you want this?

> Create Night Mode option:

Fixed in 2.0

> Add an easy way to copy the current url to clipboard.

https://github.com/sonnyp/Tangram/issues/210

> Maybe add support to define a custom icon

Maybe for #73 

> Provide a way to export and import sites.

Feedback needed https://github.com/sonnyp/Tangram/issues/201
