### ISSUE TITLE
some types of video aren't loading

### ISSUE THREAD

**Issue by Tainan404** [sonnyp/Tangram#125]
Videos in webk.telegram.org and twitter.com aren't loading in app ([sample](https://twitter.com/i/status/1404772224167407624)), I don't know how to debug to provide more infomation, but I'm avaible to help if theres anyway to provide more information. (I tested in another browser and the videos load well)

https://user-images.githubusercontent.com/15806883/122054319-f18d1480-cdbd-11eb-94ff-323525b9b1fa.mp4

**Tangram version**
re.sonny.Tangram
1.3.1

**Linux distribution**

Ubuntu 18

**Flatpak version**

Flatpak 1.6.5

**Desktop environment**

GNOME 3.36.8

**Comment by sonnyp** [comment]
From the README.md

> Before submitting a compatibility issue with a Website, please try to reproduce it with GNOME Web. If you can, report the issue to WebKitGTK, the Web engine behind Tangram and GNOME Web.

**Comment by Tainan404** [comment]
It's working on the gnome web

https://user-images.githubusercontent.com/15806883/122259196-4a38dc00-cea8-11eb-8964-207cab0775ba.mp4

**Comment by sonnyp** [comment]
Thanks - is that GNOME Web Flatpak ? Which version ?

**Comment by sonnyp** [comment]
I can reproduce the issue in GNOME Web (non-flatpak - Fedora 34) 40.1

Looks like it may be a regression in WebkitGTK

Could you share the WebkitGTK versions from both Tangram and GNOME Web?

In both cases you can find it in the about dialogs.

**Comment by Tainan404** [comment]
Tangram: WebKitGTK 2.32.1
Gnome Web: WebKitGTK 2.32.1

**Comment by sonnyp** [comment]
Yeah I can reproduce with GNOME Web 40.1 / WebkitGTK 2.32.1

**Comment by sonnyp** [comment]
I'd suggest taking it to the WebkitGTK people as a regression from 2.32.0 to 2.32.1

If you do so please share the link here.
