### ISSUE TITLE
Can't build Tangram

### ISSUE THREAD

**Issue by teackot** [sonnyp/Tangram#128]
**Tangram version**: [the latest commit on master](https://github.com/sonnyp/Tangram/commit/b3723e900c9711bc1d1433fe792c3b71efc6af81)

**Linux distribution**: Fedora 34

**Flatpak version**: Flatpak 1.10.2

**Desktop environment**: GNOME Shell 40 Wayland

When building from source, both flatpak and meson methods throw this error:

[1/4] Generating re.sonny.Tangram.src_gresource with a custom command
FAILED: src/re.sonny.Tangram.src.gresource 
/usr/bin/glib-compile-resources ../src/re.sonny.Tangram.src.gresource.xml --sourcedir ../src --internal --generate --target src/re.sonny.Tangram.src.gresource --dependency-file src/re.sonny.Tangram.src.gresource.d
../src/re.sonny.Tangram.src.gresource.xml: **Failed to locate “main.js” in any source directory.**
[4/4] Generating re.sonny.Tangram.desktop_data_merge with a custom command
ninja: build stopped: subcommand failed.
Error: module Tangram: Дочерний процесс завершился с кодом 1

**Comment by teackot** [comment]
However, running with `make dev` is working

**Comment by pervoj** [comment]
It's because the main file is called `index.js` instead of `main.js`. Maybe try to run the `run.sh` script.

**Comment by sonnyp** [comment]
Ha yes. Will fix.

Please run `./node_modules/.bin/rollup -c` meanwhile before building with flatpak or meson.

**Comment by sonnyp** [comment]
`master` was renamed `main`

Tangram does not use rollup anymore so this is fixed.
