### ISSUE TITLE
Application does not work

### ISSUE THREAD

**Issue by vanillajonathan** [sonnyp/Tangram#132]
The application does not seem to work. When I launch the application this is the window that appears.

![Screenshot from 2021-08-26 18-58-27](https://user-images.githubusercontent.com/10222521/131004787-3115ffb5-d369-4002-b20e-154179700f79.png)

```
$ flatpak run re.sonny.Tangram
Gjs-Message: 18:53:39.715: JS LOG: gjs 1.68.3
Gjs-Message: 18:53:39.715: JS LOG: WebKitGTK 2.32.3
Gjs-Message: 18:53:39.715: JS LOG: env: flatpak
Gjs-Message: 18:53:39.715: JS LOG: data_dir: /home/anonymous/.var/app/re.sonny.Tangram/data/Tangram
Gjs-Message: 18:53:39.715: JS LOG: cache_dir: /home/anonymous/.var/app/re.sonny.Tangram/cache/Tangram
Gjs-Message: 18:53:39.715: JS LOG: config_dir: /home/anonymous/.var/app/re.sonny.Tangram/config/Tangram
Gjs-Message: 18:53:39.716: JS LOG: applications_dir: /home/anonymous/.local/share/applications
Gjs-Message: 18:53:39.716: JS LOG: keyfile_settings_path: 
Gjs-Message: 18:53:39.719: JS LOG: bin: re.sonny.Tangram
Gjs-Message: 18:53:39.719: JS LOG: default_icon: re.sonny.Tangram
Gjs-Message: 18:53:39.719: JS LOG: flag TANGRAM_ENABLE_CUSTOM_APPLICATIONS false
Gjs-Message: 18:53:39.719: JS LOG: flag TANGRAM_ENABLE_CUSTOM_ICONS false
Gjs-Message: 18:53:39.724: JS LOG: programInvocationName: /app/bin/re.sonny.Tangram
Gjs-Message: 18:53:39.724: JS LOG: _: /usr/bin/flatpak
Gjs-Message: 18:53:39.724: JS LOG: pkg.datadir: /app/share
Gjs-Message: 18:53:39.724: JS LOG: pkg.name: re.sonny.Tangram
Gjs-Message: 18:53:39.724: JS LOG: pkg.pkgdatadir: /app/share/Tangram
Gjs-Message: 18:53:39.724: JS LOG: pkg.libdir: /app/lib
Gjs-Message: 18:53:39.724: JS LOG: pkg.localedir: /app/share/locale
Gjs-Message: 18:53:39.725: JS LOG: pkg.moduledir: resource:///re/sonny/Tangram/js
Gjs-Message: 18:53:39.725: JS LOG: pkg.pkglibdir: /app/lib/Tangram
Gjs-Message: 18:53:39.725: JS LOG: pkg.version: 1.3.1
Gjs-Message: 18:53:39.725: JS LOG: pkg.prefix: /app
Gjs-Message: 18:53:39.725: JS LOG: argv /app/bin/re.sonny.Tangram

(re.sonny.Tangram:2): Gtk-WARNING **: 18:53:39.725: Locale not supported by C library.
	Using the fallback 'C' locale.
Gjs-Message: 18:53:39.776: JS LOG: profile.title: Tangram
Gjs-Message: 18:53:39.776: JS LOG: profile.application_id: re.sonny.Tangram
Gjs-Message: 18:53:39.776: JS LOG: profile.settings: /re/sonny/Tangram/
flatpak-spawn: Invalid byte sequence in conversion input
Try "flatpak-spawn --help" for more information.
```

**Tangram version**
1.3.1

**Linux distribution**
Ubuntu 21.10

**Flatpak version**
1.10.2

**Desktop environment**
GNOME Shell 40.2 Wayland

**Comment by sonnyp** [comment]
It works. You just need to enter a URL.

I know it's a bit confusing as a first time experience - I will move the URL bar in the middle.

**Comment by sonnyp** [comment]
https://github.com/sonnyp/Tangram/issues/65

**Comment by vanillajonathan** [comment]
@sonnyp I am not sure it does. The "Done" button is disabled and cannot be clicked.
I don't know what I am suppose to enter, but when I enter `https://github.com/` or `https://keep.google.com/` and press Enter nothing happens. Even after entering a URL the Done button remains disabled.

When there is nothing added and it is all empty, then add a placeholder as suggested by the GNOME HIG.
https://developer.gnome.org/hig/patterns/feedback/placeholders.html

**Comment by vanillajonathan** [comment]
@sonnyp This is a bug that occurs when it says the locale is not supported.

    (re.sonny.Tangram:2): Gtk-WARNING **: 18:53:39.725: Locale not supported by C library.
	Using the fallback 'C' locale.

The application works fine when I override the PS1 environment variable:

    $ echo $PS1
    \[\e]0;\u@\h: \w\a\]${debian_chroot:+($debian_chroot)}\u@\h:\w\$
    $ flatpak run --env=PS1="\$" re.sonny.Tangram

There is an issue on Epiphany that https://github.com/flathub/org.gnome.Epiphany/issues/21 that indicated it has to do with mixed locales.

**Comment by sonnyp** [comment]
I see, ok there is nothing I can do about this https://github.com/flathub/org.gnome.Epiphany/issues/21#issuecomment-814079653

For future users affected by this, until Flatpak solves the issue and makes it into your OS, you can use [Flatseal](https://flathub.org/apps/details/com.github.tchx84.Flatseal) to set environment variable `LC_ALL="en_US.UTF-8"` to Tangram.
