### ISSUE TITLE
User-discoverable web apps

### ISSUE THREAD

**Issue by vanillajonathan** [sonnyp/Tangram#134]
Tangram could have a feature for users to discover web apps. This could be implemented either as auto-completion in the URL bar, or as a built-in predefined collection (list or grid?) of web apps which the user would be presented with and the user could pick from to add.

Having to manually enter the URL is a bit user-unfriendly. Having a collection of predefined entries that the user can pick from makes it easier for the user to quickly get started with Tangram.

- Gmail
- Google Calendar
- Google Chat
- Google Contacts
- Google Duo
- Google Drive
- Google Earth
- Google Keep
- Google Maps
- Google Meet
- Google Photos
- Google Podcasts
- Google Docs
- Google Sheets
- Google Slides
- Google Forms
- Google Collections

More
- Discord
- Element
- Facebook
- Facebook Messenger
- Steam Chat
- Telegram
- Twitter
- WhatsApp

PWA can be found at:
https://www.pwalist.app/
https://github.com/hemanth/awesome-pwa#apps

**Comment by sonnyp** [comment]
That's what the first version of Tangram did but I'm uncomfortable with recommending apps or distributing copyrighted material.

Also, Tangram isn't a great platform for running web apps and I don't necessary want to continue promoting it as such. It's misleading to the users. I think I'll replace "Run web apps on your desktop." with "An application for your pinned tabs". Many web apps simply won't run in Tangram or with subpar performances.

It's trivial to find what you are looking for in your browser and copy paste the URL in Tangram. I have thought about replacing the URL bar with a search engine though to eliminate that step.

**Comment by vanillajonathan** [comment]
You wouldn't have to distribute any copyrighted materials, just a list of hyperlinks then fetch the images defined in the `manifest.json` file at runtime.
https://developer.mozilla.org/en-US/docs/Web/Manifest/icons
If no `manifest.json` file exists, then it's not really a PWA, but in that case you could fallback to the favicon if you want to support adding it as a tab anyways.

I am not sure you would have to *personally* recommend any specific apps, it could be "community curated". Apps/sites could be added through issues or pull requests on GitHub if given enough votes/likes, or if it fits a certain criteria.

Example:
- Must be multilingual
- Must have existed for more than 1 year
- Must have an Alexa ranking of at least _X_
- Must be available in both light and dark themes
- Must pass WCAG accessibility
- Must have a privacy policy
- Must have at least _X_ search results on Google
- Must pass safety check on some website safety checker such as URLVoid, Trend Micro Site Safety Center, Norton Safe Web, etc.
- Must have a score of at least B on the SSL Labs SSL Server Test

**Comment by sonnyp** [comment]
I thought of something like this and I think it's a nice idea and addition to the Linux desktop but it isn't Tangram.

What you are talking about is basically an app to discover and "install" curated web applications. No reason they must run in Tangram, user should be able to choose, perhaps the editor or publisher even for web apps that don't run in certain browsers.

No reason why Tangram should be an applications manager. Your desktop can already manage applications.

The term PWA is mostly confusing marketing bs from Google. A website/webapp doesn't need a manifest, it would be too much of a limiting factor to require one.

It sounds more like https://github.com/linuxmint/webapp-manager with better UX and discoverability.

**Comment by vanillajonathan** [comment]
Personally I saw the value or niche in Tangram as application for web apps. Without that, I am not sure what niche Tangram aims to fill or what the purpose of it is. Maybe Tangram needs to have a clear goal and a clearly defined scope oh what it is, what it is not, what it is for, and what it is not for.
