### ISSUE TITLE
Load websites per tab basis, not all at once

### ISSUE THREAD

**Issue by tio-trom** [sonnyp/Tangram#137]
As far as I see, right now Tangram loads all of the tabs when you open the application. This is not a good thing, since if you have tens of websites, it will slow down your computer  a lot. This can be fixed by only loading the tab that's on focus. Also, if some tabs are not really used maybe you can "pause" them somehow to avoid using too many resources, and get them "back to life" once users click the tabs.

**Comment by sonnyp** [comment]
https://github.com/sonnyp/Tangram/issues/78
