### ISSUE TITLE
Tangram does not appear to be installing properly on Pop!_OS flatpak

### ISSUE THREAD

**Issue by ntnsndr** [sonnyp/Tangram#138]
**Tangram version**   
1.3.1

**Linux distribution**   
Pop!_OS 21.04

**Flatpak version**   
1.11.2

**Desktop environment**   
GNOME 3.38.5 X11

---

I just installed Tangram via Flatpak on Pop!_OS. What I got seems to be just a generic browser window. There are no buttons or features linked to Tangram. Here is a screenshot:

![Screenshot from 2021-09-06 09-22-34](https://user-images.githubusercontent.com/8330711/132238827-ff8de104-bd52-48f3-a0c2-9aaee8acb6b5.png)

Could there be some dependencies missing of some sort?

One thing I noticed is that, although both say the version is 1.3.1 on Tangram, the release date is listed as September 12, 2020 in the Pop!_Shop's Flatpak interface, but March 26, 2021 at flatpak.org. I'm not sure what would explain this discrepancy, as I though the Pop!_Shop gets its sources straight from flatpak.org.

Thanks in advance for any advice. I'm looking forward to trying Tangram!

**Comment by sonnyp** [comment]
First time UX isn't great - you need to enter a valid URL and press Done.

Tracked in https://github.com/sonnyp/Tangram/issues/65

**Comment by ntnsndr** [comment]
Oh, okay—got it now! Yes, it would be great if the process were a bit clearer—even after the first time. Maybe change it to "add a service" or something like that.

**Comment by lobau** [comment]
The empty view could be a nice placeholder explaining how to get started. Happy to try something :)

**Comment by sonnyp** [comment]
> Happy to try something :)

You're very welcome to. I don't know when/if I'll have the time to do https://github.com/sonnyp/Tangram/issues/65 so it would be a great solution in the meantime.

https://developer.gnome.org/hig/patterns/feedback/placeholders.html
