### ISSUE TITLE
Windows & MacOS Builds/Releases

### ISSUE THREAD

**Issue by trymeouteh** [sonnyp/Tangram#141]
Please release this app for Windows and MacOS

**Comment by niutech** [comment]
The easiest way to run Tangram in Windows 10 is to run it in WSL similar to [GNOME Web](http://browsingthenet.blogspot.com/2016/11/how-to-run-epiphany-web-browser-in.html).

**Comment by niutech** [comment]
This is a question for @trymeouteh, but from my POV all those alternatives are based on Electron/Blink, which is more bloated than WebKitGTK+.

**Comment by lens0021** [comment]
I've come here because Rambox's community edition is archived and Wavebox 10 is closed source, and Station doesn't seem to be in active development.

**Comment by niutech** [comment]
There are also: Ferdi(um), Franz.

**Comment by katastrophe92** [comment]
Ohh NOOOOOO ☹ I use Ferdium but is slow, too full of stuff and not clean but is FOSS. What FOSS alternative are for Windows?  Pls someone make a .exe version ❤️ Thanks

**Comment by niutech** [comment]
There is also Hamsket or you can customize Firefox using CSS to look like Tangram [which I did](https://www.reddit.com/r/browsers/comments/ydrpxp/what_do_you_think_of_web_apps_browser_like/).
