### ISSUE TITLE
Allow grouping tabs

### ISSUE THREAD

**Issue by JayDoubleu** [sonnyp/Tangram#144]
It would be awesome if Tangram would support grouping and expanding/collapsing tabs.
I find this very useful for number of work and personal projects and it would be great to be able to group it.
I would often screen share and I would rather not show personal tabs in these calls.

Currently i'm using fedora toolbox so I can have multiple instances running but perhaps it would be useful feature to either support tab grouping or profile selection.

**Comment by sonnyp** [comment]
A goal was to allow users to create Tangram applications, with their own name, icon, desktop file and of course tabs.

Would this work for you ? It's still a WIP but I'm looking forward it for myself.

See https://github.com/sonnyp/Tangram/issues/21

**Comment by JayDoubleu** [comment]
I see, the #21 looks nice and will achieve the isolation. Tab grouping would be quite useful.

Similar to what MS Teams do with their Team/Channels.
Team (Group) is collapsible:
![image](https://user-images.githubusercontent.com/40270505/137358098-f592eb9a-45fc-43f4-a085-b625f156d9b2.png)

Perhaps the collapsed groups would not be "live" or refreshed until expanded etc.

**Comment by sonnyp** [comment]
https://github.com/sonnyp/Tangram/issues/21 will cover this use case
