### ISSUE TITLE
Widevine DRM Support

### ISSUE THREAD

**Issue by matteoturini** [sonnyp/Tangram#146]
Please include (to the best of your knowledge) the following information:

**Tangram version**

1.3.1

**Linux distribution**

Arch Linux

**Flatpak version**

N/A, using AUR

**Desktop environment**

GNOME 40 X11

Please add Widevine DRM support for Spotify, Netflix, and other proprietary apps requiring DRM. Thanks.

**Comment by sonnyp** [comment]
https://gitlab.gnome.org/GNOME/epiphany/-/issues/1200
