### ISSUE TITLE
Tangram Shows White Screen Instead of Apps, Solus 4.3

### ISSUE THREAD

**Issue by MaoDzeDun** [sonnyp/Tangram#149]
Tangram all of a sudden stopped showing anything in the individual tabs. Just blank view. Interestingly enough, if you try to add a new app, it loads it normally and then in a couple of seconds goes blank, even before actually adding it.

Edit: I am not getting any notifications from WhatsApp in my system notifications, anymore, so I don't think the problem is merely a graphical bug.

Tangram version - 1.3.1

Linux distribution - Solus 4.3 

Flatpak version - 1.10.3

Desktop environment - Budgie

![Screenshot from 2021-10-21 23-18-53](https://user-images.githubusercontent.com/4119494/138351019-6aa8db67-0c81-4f23-851e-f9a65bf601d2.png)

**Comment by MaoDzeDun** [comment]
I realized I never provided the terminal output. Here are what error I get when I run Tangram through terminal:

flatpak run re.sonny.Tangram
Gjs-Message: 23:01:25.927: JS LOG: gjs 1.70.0
Gjs-Message: 23:01:25.927: JS LOG: WebKitGTK 2.33.91
Gjs-Message: 23:01:25.927: JS LOG: env: flatpak
Gjs-Message: 23:01:25.927: JS LOG: data_dir: /home/mao_dze_dun/.var/app/re.sonny.Tangram/data/Tangram
Gjs-Message: 23:01:25.927: JS LOG: cache_dir: /home/mao_dze_dun/.var/app/re.sonny.Tangram/cache/Tangram
Gjs-Message: 23:01:25.928: JS LOG: config_dir: /home/mao_dze_dun/.var/app/re.sonny.Tangram/config/Tangram
Gjs-Message: 23:01:25.928: JS LOG: applications_dir: /home/mao_dze_dun/.local/share/applications
Gjs-Message: 23:01:25.928: JS LOG: keyfile_settings_path: 
Gjs-Message: 23:01:25.930: JS LOG: bin: re.sonny.Tangram
Gjs-Message: 23:01:25.930: JS LOG: default_icon: re.sonny.Tangram
Gjs-Message: 23:01:25.930: JS LOG: flag TANGRAM_ENABLE_CUSTOM_APPLICATIONS false
Gjs-Message: 23:01:25.930: JS LOG: flag TANGRAM_ENABLE_CUSTOM_ICONS false
Gjs-Message: 23:01:25.933: JS LOG: programInvocationName: /app/bin/re.sonny.Tangram
Gjs-Message: 23:01:25.933: JS LOG: _: /usr/bin/flatpak
Gjs-Message: 23:01:25.933: JS LOG: pkg.name: re.sonny.Tangram
Gjs-Message: 23:01:25.933: JS LOG: pkg.datadir: /app/share
Gjs-Message: 23:01:25.933: JS LOG: pkg.libdir: /app/lib
Gjs-Message: 23:01:25.933: JS LOG: pkg.localedir: /app/share/locale
Gjs-Message: 23:01:25.933: JS LOG: pkg.moduledir: resource:///re/sonny/Tangram/js
Gjs-Message: 23:01:25.933: JS LOG: pkg.pkglibdir: /app/lib/Tangram
Gjs-Message: 23:01:25.933: JS LOG: pkg.version: 1.3.2
Gjs-Message: 23:01:25.933: JS LOG: pkg.prefix: /app
Gjs-Message: 23:01:25.933: JS LOG: pkg.pkgdatadir: /app/share/Tangram
Gjs-Message: 23:01:25.933: JS LOG: argv /app/bin/re.sonny.Tangram
Gtk-Message: 23:01:25.961: Failed to load module "canberra-gtk-module"
Gtk-Message: 23:01:25.975: Failed to load module "canberra-gtk-module"
Gjs-Message: 23:01:25.978: JS LOG: profile.title: Tangram
Gjs-Message: 23:01:25.978: JS LOG: profile.application_id: re.sonny.Tangram
Gjs-Message: 23:01:25.978: JS LOG: profile.settings: /re/sonny/Tangram/
Failed to open /home/mao_dze_dun/.var/app/re.sonny.Tangram/data/Tangram/069b5cdf764f487d9d18e45b045c2aeb to expose in sandbox
Gtk-Message: 23:02:07.714: Failed to load module "canberra-gtk-module"
Gtk-Message: 23:02:07.715: Failed to load module "canberra-gtk-module"
libEGL warning: DRI3: Screen seems not DRI3 capable
libEGL warning: DRI2: failed to authenticate

(WebKitWebProcess:2): Gdk-WARNING **: 23:02:08.333: The program 'WebKitWebProcess' received an X Window System error.
This probably reflects a bug in the program.
The error was '167'.
  (Details: serial 199 error_code 167 request_code 152 (unknown) minor_code 21)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)

(re.sonny.Tangram:2): Gjs-WARNING **: 23:02:40.851: JS ERROR: WebKit2.JavascriptError: 
promiseTask/</<@resource:///re/sonny/Tangram/js/main.js:356:39
main@resource:///re/sonny/Tangram/js/main.js:2728:22
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
start@resource:///org/gnome/gjs/modules/script/package.js:190:8
@/app/bin/re.sonny.Tangram:2:17


(re.sonny.Tangram:2): Gjs-WARNING **: 23:02:40.852: JS ERROR: WebKit2.JavascriptError: 
promiseTask/</<@resource:///re/sonny/Tangram/js/main.js:356:39
main@resource:///re/sonny/Tangram/js/main.js:2728:22
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
start@resource:///org/gnome/gjs/modules/script/package.js:190:8
@/app/bin/re.sonny.Tangram:2:17


(re.sonny.Tangram:2): Gjs-WARNING **: 23:02:40.852: JS ERROR: Error: Argument base may not be null
resolveURI@resource:///re/sonny/Tangram/js/main.js:1406:19
getWebAppInfo@resource:///re/sonny/Tangram/js/main.js:1417:14
async*onAddTab@resource:///re/sonny/Tangram/js/main.js:2388:24
Header/<@resource:///re/sonny/Tangram/js/main.js:2115:5
main@resource:///re/sonny/Tangram/js/main.js:2728:22
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
start@resource:///org/gnome/gjs/modules/script/package.js:190:8
@/app/bin/re.sonny.Tangram:2:17

**Comment by GamstutzCH** [comment]
Had the same issue, have you tried updating it on flathub? Fixed it for me.
(flatpak update re.sonny.Tangram
)
