### ISSUE TITLE
Tangram notifications are urgent

### ISSUE THREAD

**Issue by dancojocaru2000** [sonnyp/Tangram#155]
Notifications sent from websites from Tangram are urgent (don't time out).

---

**Tangram version**

1.3.2

**Linux distribution**

Fedora 34

**Flatpak version**

Flatpak 1.10.5

**Desktop environment**

i3

**Comment by sonnyp** [comment]
What do you expect instead ?

**Comment by dancojocaru2000** [comment]
A normal priority notification that automatically disappears after a couple of seconds and I can view later in the notification panel.

**Comment by sonnyp** [comment]
Wanna give this a try? Should be easy.

https://github.com/sonnyp/Tangram/blob/256cf90f7334106986e56d5efc1065f7523e63f9/src/window.js#L139

https://docs.gtk.org/gio/enum.NotificationPriority.html
