### ISSUE TITLE
Feature Request: Dynamic Hiding of the webapp selector

### ISSUE THREAD

**Issue by vega-d** [sonnyp/Tangram#158]
It would be great if when app is resized to be small it hid the bar into a burger menu. Would also improve usability on mobile.

![image](https://user-images.githubusercontent.com/35414314/141676437-e0071c6a-f4d5-4712-8ae7-c101ff6c28e6.png)

**Comment by sonnyp** [comment]
Duplicate of https://github.com/sonnyp/Tangram/issues/87
