### ISSUE TITLE
window does not match system theme

### ISSUE THREAD

**Issue by wgicio** [sonnyp/Tangram#159]
should the Tangram window match the system theme? Not sure if its a feature or a bug. see image
![image](https://user-images.githubusercontent.com/65882937/141743968-2e1bdb12-085a-4ea7-97b5-af65c01810ac.png)

**Comment by lobau** [comment]
If you installed Tangram using flatpak, you will need to install the Flatpak Yaru theme too

https://ubuntuhandbook.org/index.php/2021/10/enable-dark-flatpak-apps-ubuntu-linux-mint/
