### ISSUE TITLE
Gmail unsupported browser

### ISSUE THREAD

**Issue by bitfanatic** [sonnyp/Tangram#162]
Hi i am running Tangram on this type of system
**Tangram version1.3.2**.

**Linux distribution Pop os**

**Flatpak version 1.11.2**

**Desktop environment 3.38.5 Pop os Cosmic**

i am having trouble using Tangram with Gmail.com
it redirects me to a simpel html version of gmail and teels me that my browser is not supported.

is there a way to fix this issue 
thank you 
 
![Screenshot from 2021-11-20 14-07-40](https://user-images.githubusercontent.com/32371456/142727521-92a3d465-e415-425d-bcfb-93e7124eeca5.png)

**Comment by bitfanatic** [comment]
i tried leaving user agent space blank and it is working now 

i think thats why its working.

can anybody confirm that could be the reason 

thank you

**Comment by sonnyp** [comment]
If it's working it is solved?

**Comment by bitfanatic** [comment]
Yes its Solved🙂
