### ISSUE TITLE
Slack not supported anymore

### ISSUE THREAD

**Issue by jalabaya** [sonnyp/Tangram#166]
Please include (to the best of your knowledge) the following information:

**Tangram version**
1.0.1

**Linux distribution**
Debian 5.10.70-1 (2021-09-30) i686 GNU/Linux
Devuan 4 chimaera

**Flatpak version**
Flatpak 1.10.5

**Desktop environment**
LXQT (30)

So, I had Tangram working with Slack on an older PC, but now I set up this "new" one and Slack is telling me the browser is not supported. The software used on the older PC was not the latest distro version, but otherwise the same general setup. The new PC is the latest distro and other versions, as far as I can tell. (I ran `flatpak update` and ` apt update / upgrade`). Unfortunately, I can not check the versions on the older PC, as it is bricked.

**Comment by sonnyp** [comment]
Upgrade Tangram to 1.4.0

**Comment by jalabaya** [comment]
I tried. I get:

`flatpak update
Looking for updates…
Info: org.gnome.Platform//3.32 is end-of-life, with reason:
   The GNOME 3.32 runtime is no longer supported as of 11th March 2020. Please ask your application developer to migrate to a supported platform.
Applications using this runtime:
   re.sonny.Tangram
Info: org.freedesktop.Platform.html5-codecs//18.08 is end-of-life, with reason:
   The Freedesktop SDK 18.08 runtime is no longer supported as of 31th August 2020. Please ask your application developer to migrate to a supported platform.
Nothing to do.
`

But I am guessing that error is not within the scope of this repo.

**Comment by sonnyp** [comment]
Nope - sorry.

**Comment by jalabaya** [comment]
Thanks. I uninstalled for now.

**Comment by jalabaya** [comment]
Fixed by changing to a 64bit CPU and OS.
