### ISSUE TITLE
Feature request - Collapsable app groups or Enable/disable apps

### ISSUE THREAD

**Issue by scarreira-dg** [sonnyp/Tangram#168]
Hello, first of all nice app.

I have been using Tangram for like 2 weeks and I think that it would be great to have collapsable menus to organize apps like (work/personal, etc) or to have a settings menu where you could enable and disable apps to be shown. Instead of requiring to remove and add them.

Use case: I use tangram for social media due to the decrement in tracking that it provides. But I also would like to use it for work chats and apps, because it does use much less resources than a electron based solution. Right now there is the need to mix both the concepts in a long list. I can imagine other use cases like Dev Apps/Porduction Apps, etc.

Thank you.

**Comment by sonnyp** [comment]
https://github.com/sonnyp/Tangram/issues/150
