### ISSUE TITLE
run.sh - Bad substitution - Line 13

### ISSUE THREAD

**Issue by ashleycawley** [sonnyp/Tangram#169]
Please include (to the best of your knowledge) the following information:

**v.1.4.0**

See `About Tangram` in the application.

**Ubuntu 20.04 LTS**

**Flatpak 1.6.5**

`flatpak --version`

**Desktop environment**

Example `GNOME Shell 3.24 Wayland`

acawley@ashley-ubuntu-laptop:~/Downloads/Tangram$ ./run.sh 
./run.sh: 13: Bad substitution

Line 13 of that sh being:
```sed -i "/^Exec=/s/=.*/=${PWD//\//\\/}\/src\/re\.sonny\.Tangram/" re.sonny.Tangram.desktop```

**Comment by sonnyp** [comment]
Why do you use `run.sh` ?

Use GNOME Builder if you want to do development on Tangram.

**Comment by sonnyp** [comment]
If you want to solve the problem feel free to send a PR but I can't support every possible distribution for the development setup myself.

**Comment by ashleycawley** [comment]
I wasn't trying to do Dev on it, I was merely trying to use it, I thought I was following the instructions to install it, but now I see the instructions might have been under a _Development_ sub-menu, that confusion and it not working resulted in me not using it. I dislike Flatpaks and Snaps so I was probably scrolling down looking for alternative installation methods, saw _Install packages_, _Install dependencies_ and then a _run.sh_ and thought that was a viable alternative, but apparently not.

**Comment by sonnyp** [comment]
I see, thanks for explaining - I will try to make it more obvious it's the development instructions.

I only support Flatpak (which is awesome BTW, yes also for users :smile: ) but it should be trivial to package Tangram for your distribution given it's a very standard GNOME/meson app.

**Comment by ashleycawley** [comment]
Thanks for the reply. In my experience on Ubuntu and Zorin OS I've often found flatpaks or snaps to have inferior user experiences, giving issues around window resizing or lacking features the equivalent apt builds offer. Linux packaging is in a bit of a sorry [state](https://forum.zorin.com/t/differences-between-snap-appimage-and-flatpak/10021/3?u=acawley) imho.
