### ISSUE TITLE
letsencrypt certificate not accepted.

### ISSUE THREAD

**Issue by adrianuswarmenhoven** [sonnyp/Tangram#174]
**Tangram version**

1.4.0

**Linux distribution**

Ubuntu 20.04

**Flatpak version**

Flatpak 1.6.5

**Desktop environment**

XFCE

**Description**
When using a certificate issued by letsencrypt Tangram shows 'Unacceptable TLS certificate'
The validity can be checked with other browsers though.

Issuer: CN = R3, O = Let's Encrypt, C = US
CA Key ID: 14 2E B3 17 B7 58 56 CB AE 50 09 40 E6 1F AF 9D 8B 14 C2 C6
OCSP Responder: URI: http://r3.o.lencr.org
CA Issuers: URI: http://r3.i.lencr.org/

Maybe adding letsencrypt as a CA? Or is this a webkit issue?

**Comment by sonnyp** [comment]
Can you share the URL of a website to reproduce ?

**Comment by adrianuswarmenhoven** [comment]
It is a letsencrypt certificate for a local IP address/local DNS name.
If it helps I can generate a certificate for you so you can reproduce it yourself.

**Comment by sonnyp** [comment]
can you reproduce in GNOME Web/epiphany?

**Comment by sonnyp** [comment]
>  GNOME Web does however think bad about the certificate.

Then it's not a problem in Tangram sorry.

> No, insofar as that in GNOME Web I get a page where I can accept the risk and continue. 

https://github.com/sonnyp/Tangram/issues/139

**Comment by adrianuswarmenhoven** [comment]
Understood. Thank you.
