### ISSUE TITLE
Unable to attach files to Outlook mail

### ISSUE THREAD

**Issue by goznalo-git** [sonnyp/Tangram#175]
Hi there,

This app is incredibly useful for easy access to my workplace's Outlook. However, I am unable to attach any file from my system to my emails (no matter the type of file). Outlook says something like: "The following files couldn't be attached: document1.pdf, image2.pdf. Please try again later.". I always have to go to a non-tangram alternative (e.g. thunderbird or a web browser) for this, and it is quite annoying.

You can find relevant information in what follows, any other info I could provide please let me know.

Best regards,
Gonzalo

INFO:
**Tangram version:** 1.4.0
**Linux distribution:** Fedora 35 
**Flatpak version:** 1.12.4
**Desktop environment**: GNOME Shell 41.3 Wayland

**Comment by sonnyp** [comment]
Can you reproduce in GNOME Web / epiphany?

**Comment by goznalo-git** [comment]
I just installed the flatpak version of Gnome web, and I can attach files without any problem. Then I deleted it and installed the rpm version of it. Again, I could attach files.

**Comment by sonnyp** [comment]
Should be fixed in 1.5.

Please test and report back

**Comment by goznalo-git** [comment]
I am sorry, I no longer have access to that PC, I am afraid I can't test it.
