### ISSUE TITLE
[ Suggestion ] Folders

### ISSUE THREAD

**Issue by TGRush** [sonnyp/Tangram#179]
**whilst I was using Tangram, I was kind of annoyed I could only really use it for seperating one of my workflows (for example: my School workflow)**

So I thought "What if Tangram had Folders?"

I decided to then plan out how it would work, and make a mockup to somewhat visualise what it would look like:
1. hit the "Add" Button and in a drop-down menu, choose either "Add Tab" or "Add Folder" (similar to the hamburger button right next to it)
2. Go through the usual setup (Give it a name, notification priority, etc)
3. Select if websites within this folder should share their Cookies (Useful for Application Ecosystems, for example: Microsoft's Office Suite)
4. profit

Here's the afformentioned Mockup (very basic, I know, lol):
<img src=https://dl.uploadgram.me/620e996d62a79g?raw>

**Comment by sonnyp** [comment]
https://github.com/sonnyp/Tangram/issues/144
