### ISSUE TITLE
unable to use

### ISSUE THREAD

**Issue by FlorianLudwig** [sonnyp/Tangram#180]
**Tangram version**

`flatpak list`: 1.4.0

**Linux distribution**

`Fedora 35`

**Flatpak version**

Flatpak 1.12.5

**Desktop environment**

Example `GNOME Shell 41.3 Wayland`

**Issue**

The app looks like this after opening:

![image](https://user-images.githubusercontent.com/432263/156032552-2c6a2728-a1f3-497e-b900-e51f9f9c154b.png)

Entering a URL into the "Enter address" field, nothing happens. The "done" button is always disabled. Pressing `enter` doesn't do anything.

What am I missing? Where can I find docs on how to use Tangram?

thanks.

**Comment by sonnyp** [comment]
Do you get error messages after pressing enter if you open tangram in the terminal?

```
flatpak run re.sonny.Tangram
```


maybe related https://github.com/sonnyp/Tangram/issues/151

**Comment by FlorianLudwig** [comment]
The message:
```
flatpak-spawn: Invalid byte sequence in conversion input
Try "flatpak-spawn --help" for more information.
```

I tried #151 used:
```
WEBKIT_FORCE_SANDBOX=0
```
And got it working.

So i guess this can be closed. Yet the "done" button seems a bit broken. I had to insert an url, press enter and wait some time and only then the button would get usable.
