### ISSUE TITLE
Issue with SoundCloud: website works, but cannot login

### ISSUE THREAD

**Issue by 6-AND-9** [sonnyp/Tangram#181]
Hi there,

I'm trying to 'install' SoundCloud as an app, but I cannot login. SC works i.e. it plays music, so the website is functional, but I can't login and access my playlists etc.

Here's the error message I get during login:

> Our robots think you are a robot. 
> Try reloading the page. If you continue to have this problem, please [visit our Help center](https://help.soundcloud.com/hc/sections/115001107347-Help-Accessing-Your-Account).
> 
> Some ad-blockers interfere with our robot detection software, which can lead to us falsely identifying you as a robot. If you’re comfortable with it, you can try disabling your ad-blocker and try again.

Unfortunately, I can't fix this anyway. Not even restarting or reinstalling helps. 

Is there a way to load login cookie(s) from another browser and have Tangram be logged in that way?

To be clear, I don't think this is Tangram's fault; it seems some web services are going over their heads about 'bots' and stupid stuff like that. But I'd like to solve this anyway.

Regards,
- A

**Comment by sonnyp** [comment]
> Is there a way to load login cookie(s) from another browser and have Tangram be logged in that way?

Maybe but I'll let you figure this one out

search for cookies.sqlite 

Would be nice to share if you figure it out.
