### ISSUE TITLE
[feature] X-Type=Webapp

### ISSUE THREAD

**Issue by GreenLunar** [sonnyp/Tangram#182]
Stage 1:
.desktop launcher: (notice X-Type)
```
[Desktop Entry]
Version=2.0
X-Type=Webapp
Name=Mibbit
Comment=Easy and fast Webchat
Link=https://client01.chat.mibbit.com/
Icon=mibbit
MimeType=x-scheme-handler/irc;
Actions=Join;Direct;
```

Stage 2:
ֹUpon activation, a window of Tangram will be opened.
1) The window will not have widgets, or just a little amount of widgets necessary.
2) The window will not have sidebar/tabs.
3) The taskbar icon will not be the one of Tangram, rather the icon will be the one set by the  .desktop launcher.
4. Window will be automatically containing/isolating WebApps in an own instance/cache/cookies etc. This might be related to #135

This is an idea I'm desired to have it since 2016.
Further reading at https://gitlab.freedesktop.org/xdg/desktop-file-utils/-/issues/62

P.S. I originally wanted = to report this on [GNOME Web](https://wiki.gnome.org/Apps/Web/).  It might be relevant to it too.

**Comment by sonnyp** [comment]
This is not something Tangram can support by itself.

I suggest discussing this on https://gitlab.freedesktop.org/xdg/xdg-specs

**Comment by GreenLunar** [comment]
Do you mean software can't read custom [keys](https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s03.html) in `.desktop` unless such key, even with `X-` at its start, is supported by xdg-specs?

**Comment by sonnyp** [comment]
This needs to be implemented by a `.desktop` launcher.

You also need applications to create those `X-Type` `.desktop` files.

**Comment by GreenLunar** [comment]
> This needs to be implemented by a `.desktop` launcher.
> 

Yes, this is true, otherwise Type=Webapp will cause to a message "Invalide desktop file" upon execution attempt.
Here's another `.desktop` file:
```
[Desktop Entry]
X-WebApp=True
Version=1.0
Encoding=UTF-8
Name=Mastodon
Comment=Follow friends and discover new ones
Type=Link
URL=https://mastodon.social/auth/sign_in
Icon=mastodon
StartupNotify=true
```

> You also need applications to create those `X-Type` `.desktop` files.

The Web Browser will be responsible for this.
In addition to Pin tab, web browers will have an option to **Add (to menu/launcher) as WebApp**.
