### ISSUE TITLE
v1.4.1 seems to not be creating parent directories

### ISSUE THREAD

**Issue by austinbutler** [sonnyp/Tangram#188]
I get `Error creating directory /home/austin/.local/share/Tangram/f0a8761aa5e44b82b1371c77be40cc17: No such file or directory`. So I checked `/home/austin/.local/share/Tangram/`, doesn't exist. I run `mkdir /home/austin/.local/share/Tangram`, that error goes away, but up next is `home/austin/.cache/Tangram/30864ce5669b480b8f506cbe5645a9b3: No such file or directory`. Once again I create the parent directory, error goes away. So I think https://github.com/sonnyp/Tangram/commit/ddee93cceb78a2c14507c880d857d244d864c25f may be trying to directly create `~/.local/share/Tangram/f0a8761aa5e44b82b1371c77be40cc17`, when it needs to create `~/.local/share/Tangram` first.

**Tangram version**

1.4.1

**Linux distribution**

Arch

**Desktop environment**

`GNOME Shell 42 Wayland`

**Comment by sitemapxml** [comment]
I got a same kind of error.
Also, I have noticed that run.sh have some error on line 13. Something with sed command is not correct...

**Comment by sonnyp** [comment]
Fixed in v1.4.2
