### ISSUE TITLE
Font size super small on Manjaro KDE in Wayland

### ISSUE THREAD

**Issue by abstractionmage** [sonnyp/Tangram#199]
**Tangram version**

1.4.2

**Linux distribution**

Manjaro KDE

**Flatpak version**

1.12.7

**Desktop environment**

KDE Plasma 5.25.1 Wayland

**Screenshot**

![image](https://user-images.githubusercontent.com/37195767/179915012-196cbc0d-9b92-4cc5-9ddd-46b5e3592ba8.png)

**Comment by sonnyp** [comment]
How did you install Tangram?

**Comment by abstractionmage** [comment]
I installed the Flatpak `app/dk.tangramgames.mrrescue/x86_64/stable` from Flathub. Technically I used Manjaro's gui package manager "pamac" to do it, but I suppose the result should be the same as with the flatpak cli.

**Comment by sonnyp** [comment]
There is really nothing I can do about this. Please get in touch with Manjaro.
