### ISSUE TITLE
Some services can't load 

### ISSUE THREAD

**Issue by dessasin** [sonnyp/Tangram#2]
I've been trying the application for almost a few hours before no site was opened, some sites started to open, such as facebook and steam, but other services still do not open the video I took about the subject,and some services lack resources.

[Video:](https://streamable.com/8zjlj)

**Comment by sonnyp** [comment]
Thanks for taking the time to report the issue.

How did you install, flatpak?

**Comment by dessasin** [comment]
yes,i installed with flatpak way

**Comment by sonnyp** [comment]
Could you run gigagram from the command line:

```sh
flatpak run re.sonny.gigagram
```

reproduce and share the terminal output?

**Comment by dessasin** [comment]
terminal output 

`(WebKitWebProcess:170): Gdk-ERROR **: 15:36:02.865: The program 'WebKitWebProcess' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadValue (integer parameter out of range for operation)'.
  (Details: serial 196 error_code 2 request_code 152 (GLX) minor_code 34)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)


`

**Comment by sonnyp** [comment]
Ah ok, I didn't test with X11, only on Wayland, I'll try to debug.

**Comment by mustafapc19** [comment]
`https://askubuntu.com/questions/425318/eclipse-crashes-with-x-window-system-error-using-nx-cairo-the-solution`
`https://bugzilla.redhat.com/show_bug.cgi?id=1311519`

I guess this should be the problems. But the bug is maybe distro specific. I haven't tested in X-server yet. 

> I've been trying the application for almost a few hours before no site was opened, some sites started to open, such as facebook and steam, but other services still do not open the video I took about the subject,and some services lack resources.

Video is not loading. Can u give info about your distro though?

**Comment by sonnyp** [comment]
from the video @dessasin distro is Pop!_OS 19.04

**Comment by dessasin** [comment]
> `https://askubuntu.com/questions/425318/eclipse-crashes-with-x-window-system-error-using-nx-cairo-the-solution`
> `https://bugzilla.redhat.com/show_bug.cgi?id=1311519`
> 
> I guess this should be the problems. But the bug is maybe distro specific. I haven't tested in X-server yet.
> 
> > I've been trying the application for almost a few hours before no site was opened, some sites started to open, such as facebook and steam, but other services still do not open the video I took about the subject,and some services lack resources.
> 
> Video is not loading. Can u give info about your distro though?

distro:Pop os 19.04
Kernel: 5.0.0.21 generic
open video link : [https://streamable.com/8zjlj](https://streamable.com/8zjlj )

**Comment by sonnyp** [comment]
can you try with version >= 0.4.1 https://github.com/sonnyp/gigagram/releases ?
