### ISSUE TITLE
Point release for Translations

### ISSUE THREAD

**Issue by libreajans** [sonnyp/Tangram#200]
Hi @sonnyp 

Could you make a point release for translations? 17 languages had been translated. It may help improve the user experience.

**Comment by sonnyp** [comment]
Hi

Would love to, but the new release of Tangram is blocked by WebKit GTK4 port https://bugs.webkit.org/show_bug.cgi?id=210100
It's making progress, but it might be a while still.

I'll make sure the translations are included in the next release, thought.
