### ISSUE TITLE
[History] Each tab has the empty page in its history, but shouldn't

### ISSUE THREAD

**Issue by pvarga-dni** [sonnyp/Tangram#211]
Each tab has the `Back` button in enabled state from its inception and the user able to navigate back to the empty page.

I think when a tab is added, its history should begin with the URL used and not the empty page.

**Comment by sonnyp** [comment]
I can't reproduce with `example.org`

Why did you skip the issue template? There is a reason for it.

Please fill it and provide exact steps to reproduce - a screencast would be helpful too

https://github.com/sonnyp/Tangram/issues/new?assignees=&labels=&template=bug_report.md&title=
