### ISSUE TITLE
[History] Newly added tab's history starts with the empty page, but should start with the URL entered

### ISSUE THREAD

**Issue by vp2177** [sonnyp/Tangram#212]
[video demonstrating the issue](https://user-images.githubusercontent.com/451903/213293406-4204b7df-bb64-48ba-be0b-401da397c63b.webm)

I think when a tab is added, its history should begin with the URL used, not the empty page.

**Tangram version**

1.5.0

**Linux distribution**

Ubuntu 22.10

**Flatpak version**

1.14.0

**Desktop environment**

GNOME Shell 43.1 Wayland

**Comment by sonnyp** [comment]
Thank you for the clear bug report.

This appears to be fixed in 2.0 which is available now on Flathub.

Could you update and confirm?

**Comment by vp2177** [comment]
Wow that was quick :tada: 
Confirming that it's fixed in 2.0. Thank you!
