### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by knoopx** [sonnyp/Tangram#214]
fresh install, just added 3 sites, telegram, whatsapp and mastodon.

![image](https://user-images.githubusercontent.com/100993/213585234-11f1ceea-0d29-46e8-949a-aa2340abdb8b.png)

**Tangram version**

2.0

**Linux distribution**

Arch

**Flatpak version**

1.15.1

**Desktop environment**

GNOME Shell 43 X11

**Comment by sonnyp** [comment]
Can you reproduce with GNOME Epihany nightly? https://wiki.gnome.org/Apps/Nightly

If so - please report the issue [there](https://github.com/sonnyp/Tangram/blob/main/.github/ISSUE_TEMPLATE/bug_report.md)

Try Wayland too.

**Comment by knoopx** [comment]
Happens on two of my machines. One is running on Intel GPU/Wayland, the other Nvidia/X11. Installing the system package instead of flatpak neither makes any difference. Will test with Epiphany and report back.

**Comment by knoopx** [comment]
![image](https://user-images.githubusercontent.com/100993/218255451-22bcac9f-315a-43a6-b69f-ba5b181399f7.png)

crashes loading telegram, displays a blank page for whatsapp and mastodon works just fine.

**Comment by knoopx** [comment]
Stable epiphany works just fine: 

![image](https://user-images.githubusercontent.com/100993/218255688-cb07c029-616d-4e36-9f62-8acacbfe2f2f.png)

**Comment by knoopx** [comment]
just playing with gnome 44 and the high cpu usage disappeared, I guess some webkit2gtk change fixed it
