### ISSUE TITLE
Issues with Deezer

### ISSUE THREAD

**Issue by nclm** [sonnyp/Tangram#219]
I would like to use Tangram with Deezer, but it’s somehow impossible because the Deezer website gets very very laggy in Tangram, to the point that I cannot even type my log-in details in the log-in page. The computer starts to ventilate and Tangram gets very slow.

I don’t have issues with other web apps in Tangram, and I don’t have issues with Deezer in other browsers.

So there might be something to investigate there?

**Tangram version**
2.0

**Linux distribution**
Ubuntu 22.10

**Flatpak version**
1.14.0

**Desktop environment**
`GNOME 43.0 Wayland`

**Comment by sonnyp** [comment]
Tangram 3.0 might solve it.

In any case - it's probably an issue with WebKitGTK

⚠️ Before submitting a compatibility issue with a Website, try to reproduce it with [GNOME Web](https://flathub.org/apps/details/org.gnome.Epiphany) first. If you can, [report the issue to WebKitGTK](https://bugs.webkit.org/enter_bug.cgi?product=WebKit&component=WebKitGTK&version=Other&op_sys=Linux), the Web engine behind Tangram and GNOME Web.
