### ISSUE TITLE
Add a tab as a desktop launcher (and separate Tangram windows?)

### ISSUE THREAD

**Issue by nclm** [sonnyp/Tangram#220]
For some web apps, I would like direct desktop access.

It would be very cool to be able to be able to say: I want this app (this tab) as a desktop launcher, and it would be added in the app launchers just like any other app, that could be favourited, or launched by typing its name, etc. Maybe a little icon in the sidebar tab list would show the special status of the apps that have been created as launchers.

Additionally, when launching an app from a launcher, we could imaging it could open a sidebar-less Tangram. And if several of these launched apps are opened, they could be separate Tangram windows?

**Comment by sonnyp** [comment]
You can use GNOME Web for that .

https://fedoramagazine.org/standalone-web-applications-gnome-web/
https://help.gnome.org/users/epiphany/stable/browse-webapps.html.en
