### ISSUE TITLE
Folder sorting?

### ISSUE THREAD

**Issue by poyo20** [sonnyp/Tangram#224]
**Tangram Version** - 2.0

**Linux distribution** - Fedora Workstation 37

**Flatpak version** - Flatpak 1.14.1

**Desktop environment** - GNOME 43 Wayland

--------------------------------------------------
Dear Sonny P.

It would be nice of you if we could sort tabs by folders. 
Like a **School** folder, 
or a **Work** folder. 
Would make sorting easier.

Sincerely, 
Random Github user

**Comment by sonnyp** [comment]
https://github.com/sonnyp/Tangram/issues/21
