### ISSUE TITLE
Window decorations and sidebar width are incorrect when using left sided titlebar buttons

### ISSUE THREAD

**Issue by Pistrie** [sonnyp/Tangram#225]
Please include (to the best of your knowledge) the following information:

**Tangram version**

2.0

**Linux distribution**

Garuda Linux

**Flatpak version**

Flatpak 1.15.1

**Desktop environment**

Plasma 5.26.5 on Wayland

---

When having the titlebar buttons on the left side of the window it breaks the look and feel of Tangram.

![image](https://user-images.githubusercontent.com/39904003/215290231-aca8127a-6747-44ad-95da-fdd432188efd.png)

Compare this with how it is supposed to look like:

![image](https://user-images.githubusercontent.com/39904003/215290291-9b9869c9-51aa-49c9-9611-e80d7a9d88f5.png)

Here is a screenshot of my Plasma settings which are causing this behaviour:

![image](https://user-images.githubusercontent.com/39904003/215290334-b9857afe-25ba-4f9e-94b0-43073f5eda92.png)

Let me know if you need more information 👍

**Comment by sonnyp** [comment]
Should be solved in Tangram 3.0
