### ISSUE TITLE
White Pinned Pages with nvidia GPU

### ISSUE THREAD

**Issue by oscar-renteria** [sonnyp/Tangram#227]
Tangram just stopped working after an update.
The pinned pages are complete white/transparent.

WebKitGTK 2.38.3
GJS 1.74.1
Adw 1.2.1
GTK 4.8.3
GLib 2.74.4
libsoup 3.2.2
GStreamer 1.20.5

![image](https://user-images.githubusercontent.com/20833418/215742307-c8b096d9-6246-416e-940a-512c2c70cd9b.png)

**Comment by sonnyp** [comment]
Try again after `flatpak update`

**Comment by oscar-renteria** [comment]
Hi, thank you for the answer. Unfortunately, `flatpack update` did not fix the issue.

**Comment by sonnyp** [comment]
Is it a white page for every tab? 

Do you happen to have an nVidia GPU ?

**Comment by oscar-renteria** [comment]
> Is it a white page for every tab?
Yes

> Do you happen to have an nVidia GPU ?
Yes

**Comment by sonnyp** [comment]
https://floss.social/@sonny/109786271802252091
https://bugs.webkit.org/show_bug.cgi?id=228268

**Comment by sonnyp** [comment]
I made a one stop pinned issue for this

https://github.com/sonnyp/Tangram/issues/234

**Comment by sonnyp** [comment]
We are looking for details on how to reproduce. 
If anyone can please comment on https://github.com/sonnyp/Tangram/issues/234
