### ISSUE TITLE
Do not save file to computer

### ISSUE THREAD

**Issue by tjapro** [sonnyp/Tangram#228]
When I tried to save a file from Whatsapp, I receive a notification about a file downloaded and saved, but there isn't any file saved.  
This do not occur on GNOME Web.

**Tangram version**
```
        ID: re.sonny.Tangram
       Ref: app/re.sonny.Tangram/x86_64/stable
      Arq.: x86_64
      Ramo: stable
    Versão: 2.0
   Licença: GPL-3.0
    Origem: flathub
   Coleção: org.flathub.Stable
Instalação: system
 Instalado: 679,4 kB
   Runtime: org.gnome.Platform/x86_64/43
       Sdk: org.gnome.Sdk/x86_64/43
```

**Linux distribution**
Fedora 37

**Flatpak version**
Flatpak 1.14.1

**Desktop environment**
GNOME Shell 42.3 Wayland

**Comment by sonnyp** [comment]
Tangram attempts to download these files to `~/Downloads` but doesn't have permission to it.
You can use Flatseal to give `~/Downloads` write access to Tangram.

I will let user choose where to download files eventually.

**Comment by ondras12345** [comment]
Hi, I have the same problem.
Ubuntu 20.04.6 LTS
Flatpak 1.6.5
GNOME 3.36.8 X11
I have added `/home/$USER/Downloads` as allowed directory using Flatseal, but it didn't help.

When I start the application from the command line and try do download something, I get the following error message:
```
$ flatpak run re.sonny.Tangram
Gjs-Message: 18:49:42.087: JS LOG: env: flatpak
Gjs-Message: 18:49:42.087: JS LOG: data_dir: /home/ondra/.var/app/re.sonny.Tangram/data/Tangram
Gjs-Message: 18:49:42.087: JS LOG: cache_dir: /home/ondra/.var/app/re.sonny.Tangram/cache/Tangram
Gjs-Message: 18:49:42.087: JS LOG: config_dir: /home/ondra/.var/app/re.sonny.Tangram/config/Tangram
Gjs-Message: 18:49:42.087: JS LOG: applications_dir: /home/ondra/.local/share/applications
Gjs-Message: 18:49:42.087: JS LOG: keyfile_settings_path: 
Gjs-Message: 18:49:42.157: JS LOG: programInvocationName: /app/bin/re.sonny.Tangram
Gjs-Message: 18:49:42.157: JS LOG: _: /usr/bin/flatpak
Gjs-Message: 18:49:42.157: JS LOG: pkg.version: 2.0
Gjs-Message: 18:49:42.157: JS LOG: pkg.pkglibdir: /app/lib/re.sonny.Tangram
Gjs-Message: 18:49:42.157: JS LOG: pkg.datadir: /app/share
Gjs-Message: 18:49:42.157: JS LOG: pkg.localedir: /app/share/locale
Gjs-Message: 18:49:42.157: JS LOG: pkg.pkgdatadir: /app/share/re.sonny.Tangram
Gjs-Message: 18:49:42.157: JS LOG: pkg.prefix: /app
Gjs-Message: 18:49:42.157: JS LOG: pkg.moduledir: resource:///re/sonny/Tangram/js
Gjs-Message: 18:49:42.157: JS LOG: pkg.name: re.sonny.Tangram
Gjs-Message: 18:49:42.157: JS LOG: pkg.libdir: /app/lib
Gjs-Message: 18:49:42.157: JS LOG: argv /app/bin/re.sonny.Tangram

(re.sonny.Tangram:2): Gjs-CRITICAL **: 18:50:21.585: JS ERROR: Error: No property do_overwrite_confirmation on GtkFileChooserNative
buildWebView/</<@resource:///re/sonny/Tangram/src/WebView.js:154:22
main@resource:///re/sonny/Tangram/src/main.js:58:22
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
@file:///app/bin/re.sonny.Tangram:28:41
@file:///app/bin/re.sonny.Tangram:34:6



```

**Comment by zrooda** [comment]
Adding only the Downloads folder permissions in Flatseal doesn't seem to work, setting `filesystem=home` for all user files does.

**Comment by tjapro** [comment]
> I will let user choose where to download files eventually.

@sonnyp , I notice this issue is closed with the new version of Tangram.  
But it seems this is not resolved, or is it need to install Flatseal to correct it?

_PS: Thanks for your hard work!_

**Comment by sonnyp** [comment]
It should be fixed.

Tangram should ask you where to download the file. See https://github.com/sonnyp/Tangram/blob/7de723ec2c9854c26561cb9abf916646e903ba98/src/WebView.js#L61

Please file a new bug report with steps to reproduce if it's not solved for you.

**Comment by munmuni** [comment]
This makes little sense, why not enable downloads to download directory initially only? Please enable if possible
