### ISSUE TITLE
Feature Request - Pull down options for User Agent & Default User Agent option

### ISSUE THREAD

**Issue by glidingthrough** [sonnyp/Tangram#229]
It's great that you can change the user agent. I use a database of user agents to copy and paste the correct user agent into the settings for the tab, however, I was wondering if it'd be possible to have pull down lists to select an appropriate user agent, for example, a Device/OS pull down list (iPhone, Android, Windows, etc.) followed by a browser pull down list (Firefox, Safari, Edge, Chrome, etc.)?

Additionally, the ability to set a default User Agent for all new tabs would also be helpful.

Many thanks for the good work - it's a very useful app to have!

**Comment by sonnyp** [comment]
Not worth the effort.
