### ISSUE TITLE
Whatsapp does not trigger notifications

### ISSUE THREAD

**Issue by stingray21** [sonnyp/Tangram#230]
**Tangram version** 2.0
**Linux distribution** Manjaro Gnome
**Desktop environment** Gnome 43 Wayland

I do get notifications for e.g. Element messenger, but not for Whatsapp. 

I tried it on the [AUR version](https://aur.archlinux.org/packages/tangram) and Flatpak

**Comment by sonnyp** [comment]
It works for me. Do you have notifications enabled in WhatsApp settings?

**Comment by stingray21** [comment]
Weird, yes, I do

**Comment by sonnyp** [comment]
I just confirmed again it works fine.

You'll have to investigate what the problem may be on your system if the issue persists.
