### ISSUE TITLE
BUG: All websites are washed out?

### ISSUE THREAD

**Issue by halfmexican** [sonnyp/Tangram#231]
Please include (to the best of your knowledge) the following information:

**Tangram version**
2.0

**Linux distribution**
Pop!_OS 22.04

**Flatpak version**
1.12.7

**Desktop environment**
GNOME 42.5

GNOME Web/Epiphany does not have this issue. All websites I visit on tangram are completely washed out. I am using gradience to theme Libadwaita but removing my custom theme did not solve this issue. I've updated everything to my knowledge

![image](https://user-images.githubusercontent.com/103920890/216707713-66ea5777-4f26-4d09-b075-ca8458c8139a.png)

![image](https://user-images.githubusercontent.com/103920890/216707739-7871bea1-47b9-4ae2-b704-b28e0ba0f1d6.png)

logs:
`josehunter@pop-os-jose:~$ flatpak run re.sonny.Tangram 
Gjs-Message: 14:46:58.315: JS LOG: env: flatpak
Gjs-Message: 14:46:58.316: JS LOG: data_dir: /home/josehunter/.var/app/re.sonny.Tangram/data/Tangram
Gjs-Message: 14:46:58.316: JS LOG: cache_dir: /home/josehunter/.var/app/re.sonny.Tangram/cache/Tangram
Gjs-Message: 14:46:58.316: JS LOG: config_dir: /home/josehunter/.var/app/re.sonny.Tangram/config/Tangram
Gjs-Message: 14:46:58.316: JS LOG: applications_dir: /home/josehunter/.local/share/applications
Gjs-Message: 14:46:58.316: JS LOG: keyfile_settings_path: 
Gjs-Message: 14:46:58.368: JS LOG: programInvocationName: /app/bin/re.sonny.Tangram
Gjs-Message: 14:46:58.368: JS LOG: _: /usr/bin/flatpak
Gjs-Message: 14:46:58.368: JS LOG: pkg.version: 2.0
Gjs-Message: 14:46:58.368: JS LOG: pkg.pkglibdir: /app/lib/re.sonny.Tangram
Gjs-Message: 14:46:58.368: JS LOG: pkg.datadir: /app/share
Gjs-Message: 14:46:58.368: JS LOG: pkg.localedir: /app/share/locale
Gjs-Message: 14:46:58.368: JS LOG: pkg.pkgdatadir: /app/share/re.sonny.Tangram
Gjs-Message: 14:46:58.368: JS LOG: pkg.prefix: /app
Gjs-Message: 14:46:58.368: JS LOG: pkg.moduledir: resource:///re/sonny/Tangram/js
Gjs-Message: 14:46:58.368: JS LOG: pkg.name: re.sonny.Tangram
Gjs-Message: 14:46:58.368: JS LOG: pkg.libdir: /app/lib
Gjs-Message: 14:46:58.368: JS LOG: argv /app/bin/re.sonny.Tangram
`

**Comment by sonnyp** [comment]
What do you mean washed out?

**Comment by halfmexican** [comment]
In the screenshots I posted, tangram displays all webpages with what appears brightness turned up and contrast turned down. The colors are completely wrong. Gnome web displays the webpages fine

**Comment by sonnyp** [comment]
I can't even tell but maybe that's because of my device or the fact you took window screenshots.

Do you have an Nvidia GPU?

**Comment by halfmexican** [comment]
Here they are side by side. Mastodon Dark theme is almost white.

![image](https://user-images.githubusercontent.com/103920890/216748109-14565998-95be-4476-987d-21a4cd2fa7ea.png)

I have a NVIDIA 3080ti and the 525 driver

**Comment by RustedAperture** [comment]
@sonnyp I can verify I'm having the same issue. Im also running nvidia drivers with x11. tested against v43 gnome-web and the issue isn't there.

**Comment by sonnyp** [comment]
I made a one stop pinned issue for this

https://github.com/sonnyp/Tangram/issues/234

**Comment by sonnyp** [comment]
We are looking for details on how to reproduce. 
If anyone can please comment on https://github.com/sonnyp/Tangram/issues/234
