### ISSUE TITLE
Open Tab and Raise Window when notification is clicked

### ISSUE THREAD

**Issue by FriederHannenheim** [sonnyp/Tangram#232]
I would like Tangram raise it's window to the top and open the tab from which a notification was sent when you click a notification. This is useful for when you get a chat message or an email and you want to quickly reply to it without having to search for the Tangram window.

**Comment by HighKingofMelons** [comment]
This is probably related to:
https://gitlab.gnome.org/GNOME/gtk/-/issues/5239
