### ISSUE TITLE
Busybox env doesn't support -S which results in the launch script exiting immediately

### ISSUE THREAD

**Issue by paper42** [sonnyp/Tangram#236]
The busybox env applet doesn't support -S, so `#!/usr/bin/env -S gjs -m` in the launch script doesn't work. Hardcoding the path to `/usr/bin/gjs` makes it work as expected. I patched this in Alpine https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/44251 because there we can be sure gjs will always be in /usr/bin/, but I am opening this issue because there might be a more universal way to do this that could be merged to this repository and Alpine wouldn't have to carry the patch.

---

**Debugging Information**

WebKit2GTK 2.38.4
GJS 1.74.1
Adw 1.2.2
GTK 4.8.3
GLib 2.74.1
libsoup 3.2.2
GStreamer 1.22.0

**Flatpak version**

this is a native package, not installed through flatpak, the flatpak package has its own version of coreutils and doesn't use env from the host, so this is not an issue

**Operating System**

PostmarketOS (Alpine Linux) Edge

**Desktop Environment**
Phosh

**Comment by sonnyp** [comment]
`#!/usr/bin/env -S gjs -m` is the recommended shebang for GJS - I'm not very keen on changing it.

I suspect Alpine will see this becoming more of an issue as GJS apps are being ported to ESM.
Couldn't busybox implement `env -S` ?

**Comment by sonnyp** [comment]
https://gitlab.com/postmarketOS/pmaports/-/merge_requests/3868
