### ISSUE TITLE
Feature request: multiple profiles

### ISSUE THREAD

**Issue by almereyda** [sonnyp/Tangram#239]
> As a Tangram user, I need to use multiple profiles, in order to differntiate multiple sets of web applications, belonging to different identities, from each other.

In Firefox, we have the `-ProfileManager` and the `-P` plus `--profile` switches, which allow to select different profiles from a list, via their name or via their path.

This is very useful, when the isolation between cookie realms within Multi-account containers is not enough. I suggest Tangram adopts this feature, in so we can manage multiple environments of sets of web applications that belong together.

**Comment by somepaulo** [comment]
Since all tabs are isolated by default, there's no real need for a totally separate and full blown profile feature, IMO. Collapsible tab groups would do just fine for the purpose of separating workflows.

**Comment by sonnyp** [comment]
https://github.com/sonnyp/Tangram/issues/21
