### ISSUE TITLE
Scroll is not working in Telegram web

### ISSUE THREAD

**Issue by mediapinta** [sonnyp/Tangram#243]
Very often the scroll in [Telegram web](https://web.telegram.org/) (Telegram WebZ 1.60.2) freeze and stop working. Both up and down, and in both columns.

I can't reproduce this bug in GNOME Web.

---

**Debugging Information**

WebKitGTK 2.38.5
GJS 1.74.1
Adw 1.2.2
GTK 4.8.3
GLib 2.74.5
libsoup 3.2.2
GStreamer 1.20.5

**Flatpak version**
Flatpak 1.12.7

**Operating System**

Ubuntu 22.04.2 LTS

**Desktop Environment**

GNOME 42.5

**Comment by sonnyp** [comment]
It's the same issue in GNOME Web 44.2

Please report the issue to WebKitGTK https://bugs.webkit.org/enter_bug.cgi?product=WebKit&component=WebKitGTK&version=Other&op_sys=Linux
