### ISSUE TITLE
Responsive and mobile UI: Don't fit the screen on my OnePlus 6T

### ISSUE THREAD

**Issue by JumpLink** [sonnyp/Tangram#245]
Tangram does not fit the screen and is too wide, see screenshots:

![tangram-overview](https://user-images.githubusercontent.com/1073989/224666569-7fee06a6-dd10-4e9d-8ee6-bd104687f149.png)
![tangram-setup-telegram](https://user-images.githubusercontent.com/1073989/224666572-dc0463bb-c858-42cf-bf51-4eb7e5b2fd5c.png)
![tangram-telegram](https://user-images.githubusercontent.com/1073989/224666578-64e6245f-9223-454b-8134-bcb2b9445208.png)

**Operating System**

PostmarketOS v22.12

**Desktop Environment**
Phosh 0.24.0

**Device**
OnePlus 6T

**Comment by sonnyp** [comment]
https://github.com/sonnyp/Tangram/issues/233
