### ISSUE TITLE
Clear WebView cache feature

### ISSUE THREAD

**Issue by philn** [sonnyp/Tangram#248]
It'd be nice to have a button somewhere allowing to clear the on-disk cache for a given WebView. Maybe somewhere in the popup open when clicking on the cog icon?

 
**Debugging Information**

WebKitGTK 2.38.5
GJS 1.74.1
Adw 1.2.2
GTK 4.8.3
GLib 2.74.5
libsoup 3.2.2
GStreamer 1.20.5

**Flatpak version**

1.14.1

**Operating System**

F37 Silverblue

**Desktop Environment**

GNOME

**Comment by sonnyp** [comment]
There are 2 shortcuts for it

`<Control><Shift>R` and `<Shift>F5`

We could also implement Ctrl + click on reload button
