### ISSUE TITLE
[Feature request] add a button or keybind to show/hide the tab sidebar

### ISSUE THREAD

**Issue by me6262** [sonnyp/Tangram#249]
sometimes i do want to have the sidebar for fast access, sometimes, I dont, the adwaita interface guidelines have f9 as the default for showing/hiding a left sidebar, so that would make it more standard with other apps too. I absolutely LOVE this app, I just would rather have less in my way when i am not actively swapping between apps. thank you in advance for your consideration, and I understand if this is not a priority or a widely desired feature.

**Comment by sonnyp** [comment]
The tab bar will probably go away.
