### ISSUE TITLE
Tangram window is extremely laggy and the website has washed out colors

### ISSUE THREAD

**Issue by dacwatson** [sonnyp/Tangram#251]
When dragging around/resizing/etc the Tangram window, it hangs and lags, not moving around properly.

Washed out colors example: 

Tangram
![image](https://user-images.githubusercontent.com/70728355/229329558-dbea4e58-672b-4685-8d82-8f36f6aacc9d.png)
vs Firefox
![image](https://user-images.githubusercontent.com/70728355/229329590-f5f8874d-f156-497e-8637-a8b07c326d33.png)
vs Epiphany
![image](https://user-images.githubusercontent.com/70728355/229329614-ed6bf2cf-4b17-4a39-af01-50c9f22362d1.png)

---

Please include (to the best of your knowledge) the following information:

**Debugging Information**

WebKitGTK 2.38.5
GJS 1.74.2
Adw 1.2.4
GTK 4.8.3
GLib 2.74.6
libsoup 3.2.2
GStreamer 1.20.5

**Flatpak version**

Flatpak 1.14.0

**Operating System**

VanillaOS 22.10 all

**Desktop Environment**

GNOME Shell 43.1 Wayland

**Comment by sonnyp** [comment]
Nvidia?

**Comment by sonnyp** [comment]
https://github.com/sonnyp/Tangram/issues/234

**Comment by sonnyp** [comment]
We are looking for details on how to reproduce. 
If anyone can please comment on https://github.com/sonnyp/Tangram/issues/234
