### ISSUE TITLE
ChatGPT

### ISSUE THREAD

**Issue by vinaooo** [sonnyp/Tangram#252]
Chp GPT keep reloading Captcha, sometimes it passes, but dont act on sigin button tap

chat gpt goes ok with GNOME web

---

Please include (to the best of your knowledge) the following information:

WebKitGTK 2.38.5
GJS 1.74.2
Adw 1.2.4
GTK 4.8.3
GLib 2.74.6
libsoup 3.2.2
GStreamer 1.20.5

You can find it via Tangram -> Menu -> About Tangram -> Troubleshooting.

**Flatpak version**

Flatpak 1.14.0

**Operating System**

Ubuntu 22.10

**Desktop Environment**

GNOME Shell 43 Wayland

**Comment by sonnyp** [comment]
Might be solved in Tangram 3.0

**Comment by vinaooo** [comment]
fixed =]
