### ISSUE TITLE
Unable to Share Clipboard Images on WhatsApp Web via 'Ctrl+V' Shortcut Using Tangram Browser

### ISSUE THREAD

**Issue by TasbasMN** [sonnyp/Tangram#256]
I'm having trouble sharing screenshots from my clipboard on WhatsApp Web using Tangram. When I try to use the keyboard shortcut 'ctrl+v' to paste the image into a chat, it doesn't work. This behavior is supported in both Firefox and Chrome, but not in Tangram.

I also managed to reproduce it with Epiphany browser. Will also report a bug there.

**Debugging Information**

WebKitGTK 2.38.5
GJS 1.74.2
Adw 1.2.4
GTK 4.8.3
GLib 2.74.6
libsoup 3.2.2
GStreamer 1.20.6

**Flatpak version**

flatpak 1.15.4

**Operating System**

Manjaro Linux

**Desktop Environment**

KDE Plasma

**Comment by sonnyp** [comment]
https://github.com/sonnyp/Tangram/issues/256
