### ISSUE TITLE
WhatsApp nor Spotify working

### ISSUE THREAD

**Issue by altnavi** [sonnyp/Tangram#257]
Chats don't load in WhatsApp and cannot use Spotify, I'm guessing, since it has DRM. Kindly ask for a pop-up to allow it in each app. Not a web-dev so I can't do anything since it'd take me to learn everything.

**Comment by sonnyp** [comment]
https://github.com/sonnyp/Tangram/issues/60

if whatsapp doesn't work - create a new issue please but it works fine for me
