### ISSUE TITLE
[Feature request] Nested collections

### ISSUE THREAD

**Issue by TriVoxel** [sonnyp/Tangram#262]
**Rationale**

The browser will quickly become crowded once enough entries have been added. It lacks any organizational features for webpages, besides simply re-ordering them. The current system feels very good to use, however, I feel like it could be more robust.

**Description**

The idea is similar to bookmarks from traditional browsers. However, instead of this being in a bookmark menu, this would be expanding the existing "Tangram" menu feature. The idea is for users to be able to create a "collection" with a custom label, then to drag and drop webapps and other collections into these collections. This would look and feel simple and intuitive, but would allow for a high degree of personalization and organization which would make people who rely on many webapps to use this app more seriously.

**Design**

My proposed design goes like this: turn the "new tab" button into a simple "+" button. Clicking this button will allow the user to decide whether to create a "New Tab" or a "New Collection" using a drop-down menu. When "New Collection" is selected, there may be a simple menu allowing the user to enter a Name, accent color, and icon. The default icon could be a symbolic globe icon, but could be overridden with some preset icons for various categories of webapps.

![Collections Mockup Merged](https://user-images.githubusercontent.com/25536957/235365415-e1e0c76e-037a-425f-8cd2-d298879fcbc9.jpg)

After creating a collection, the user simply drags and drops their webapps into it to organize it. I'm sure the Libadwaita toolkit can do better than this preview, but I thought it would help you somewhat understand what I mean. Essentially, these collections would open up a nested tab view, with the relevant tabs listed. Please let me know what you think, personally, I think this would really add a lot of functionality, and would make the app feel more personalized.

**Comment by sonnyp** [comment]
There are many issues open about some form of grouping tabs – please search the tracker before filing a new issue.

The only option I'm considering is #21
