### ISSUE TITLE
Missing sidebar

### ISSUE THREAD

**Issue by st599** [sonnyp/Tangram#267]
Sidebar of tabs is no longer shown on loading.  A number of tabs is shown, you can choose one but then you can't swap to others.  This app is now unusable.

---

Please include (to the best of your knowledge) the following information:

**Debugging Information**

WebKitGTK 2.40.1
GJS 1.76.0
Adw 1.3.2
GTK 4.10.3
GLib 2.76.2
libsoup 3.4.1
GStreamer 1.20.6

**Flatpak version**

1.14.0

**Operating System**

Ubuntu 22.10

**Desktop Environment**

GNOME 43 Wayland

**Comment by sonnyp** [comment]
Click on Tangram in the headerbar to show the list of tabs.

**Comment by ercas** [comment]
> Click on Tangram in the headerbar to show the list of tabs.

Hi! Could I ask what the reason for removing the sidebar was? It was a big selling point for Tangram for me - it sort of seems now more like a stripped-down browser with extra steps to navigate to different websites.

**Comment by eboye** [comment]
@ercas +1 for that question. I was very disappointed when I saw that tabs sidebar is missing. The whole reason I installed was that feature alone.

**Comment by trolley813** [comment]
@ercas +1 too. Now it's much less convenient to switch between the tabs, especially if you're working with several of them at once. Why not keeping both variants and allowing the user to choose between them?

**Comment by gnunn1** [comment]
+1 on this issue, clicking Tangram in the titlebar isn't intutive and requires an additional interaction over switching in a always visible sidebar. I'd love to see it come back as an option.

**Comment by ercas** [comment]
@eboye @trolley813 @gnunn1 I've been using the previous version for about a month now and it seems to work fine without issue, can run like so:

```bash
flatpak update --commit=e4a4fd76a4032685fe8dabfa6a53cebbe5eb8fd1673b42decdfe9c5413744240 re.sonny.Tangram
flatpak mask re.sonny.Tangram
```

**Comment by eboye** [comment]
Yes, you can, but that's not the point. I don't want to be stuck at some old version.

**Comment by plundration** [comment]
+1. A possible solution would be to include an option whether the user wants this feature. I would definitely want this, it is more convenient for me.
