### ISSUE TITLE
Non-flatpak Tangram 3.0 doesn't work on GNOME <44

### ISSUE THREAD

**Issue by somepaulo** [sonnyp/Tangram#269]
Trying to run the non-flatpak version of Tangram on GNOME 43 results in a critical error and crash.
`application.runAsync` is a new feature of GNOME 44, so non-flatpak users on older systems aren't able to use Tangram 3+
This will be a non-issue on Arch in a few days when 44 hits the repos, but Ubuntu LTS folks will still be affected if they can't fall back to flatpak for some reason like corporate restrictions. Don't know how big that user share is, but it might be worth thinking of a mitigation for backwards compatibility outside flatpak.

**Debugging Information**

```
$ re.sonny.Tangram
Gjs-Message: 10:54:35.957: JS LOG: env: host
Gjs-Message: 10:54:35.957: JS LOG: data_dir: /home/somepaulo/.local/share/Tangram
Gjs-Message: 10:54:35.957: JS LOG: cache_dir: /home/somepaulo/.cache/Tangram
Gjs-Message: 10:54:35.957: JS LOG: config_dir: /home/somepaulo/.config/Tangram
Gjs-Message: 10:54:35.958: JS LOG: applications_dir: /home/somepaulo/.local/share/applications
Gjs-Message: 10:54:35.958: JS LOG: keyfile_settings_path: 

(re.sonny.Tangram:229540): Gjs-CRITICAL **: 10:54:36.014: JS ERROR: TypeError: application.runAsync is not a function
main@resource:///re/sonny/Tangram/main.js:33:22
@file:///usr/bin/re.sonny.Tangram:20:25

(re.sonny.Tangram:229540): Gjs-CRITICAL **: 10:54:36.014: Module file:///usr/bin/re.sonny.Tangram threw an exception
```

**Flatpak version**

none

**Operating System**

Arch

**Desktop Environment**

GNOME Shell 43.5 Wayland

**Comment by sonnyp** [comment]
That's why Flatpak exists...

Talk to the packagers, not me.

https://github.com/sonnyp/Tangram/issues/266

**Comment by somepaulo** [comment]
Sorry for the repeat issue. Did a search for it a few days ago, but only came back to submitting today and didn't notice someone beat me to it.

> That's why Flatpak exists...

As I mentioned, some corporate users are banned from using flatpak and have to rely on repos only. Arguably, a niche use case. Don't know how big that niche is. I guess you'll figure if you keep getting reports about this.

If calling `application.runAsync` from within the installed program's `main.js` file can be disabled on GNOME <44 by packagers, then it's definitely a non-issue for you.   
Arch packagers didn't do it, though. For whatever reason. Just waiting for GNOME 44 to land.

Best of luck, and thank you for a great piece of software!

**Comment by sonnyp** [comment]
>  some corporate users are banned from using flatpak

Do you have a link/source for this? I'd be interested in discussing this with the Flathub team.

> and have to rely on repos only.

Tangram isn't packaged for Ubuntu.

> If calling application.runAsync from within the installed program's main.js file can be disabled on GNOME <44 by packagers, then it's definitely a non-issue for you.

You don't get to decide what is or isn't an issue for me.
I release Tangram under GPL, which means anyone can distribute it. What people choose to do with the code is their responsibility.

Did you read the aur comments? https://aur.archlinux.org/packages/tangram#comment-912509

> thank you for a great piece of software!

Thanks!
