### ISSUE TITLE
Gifs cause reddit to crash

### ISSUE THREAD

**Issue by codyfish** [sonnyp/Tangram#39]
An other issue I do sadly have not time to dig into next week: When browsing reddit (which I love on Tangram as I stay logged in and it is containerized even though it feels a little laggy), sometimes a restart is required.
 I figured that the reason for this are gifs (In e.g. WhatsApp they work fine). In firefox they work well, but in epiphany (which should be kind of webkitgtk?) the site crashes, so there's probably not much you can do about it. Might be related to this [issue about reddit requiring reloads ](https://github.com/sonnyp/Tangram/issues/17)

Edit: 
I experimented a little more, and it seems that only reddit causes this in epiphany and WebKitGTK both.

**Comment by sonnyp** [comment]
Related: https://www.reddit.com/r/gnome/comments/cbzrhg/i_made_my_first_gnome_app_a_ramboxfranz_clone/etjlrh7/

Are the gifs in autoplay? We could disable gifs autoplay.

**Comment by sonnyp** [comment]
Okay I can reproduce simply by loading https://www.reddit.com/r/gifs/ in Tangram or Epiphany. The difference is that Tangram does not show anything when the Web process crashes so the tab becomes an empty area.

**Comment by sonnyp** [comment]
`settings.set_media_playback_requires_user_gesture(true);` in `src/tab.js` `function TabPage` prevents the crash.

**Comment by sonnyp** [comment]
On my computer hitting play result in the video rendering incorrectly:

![Screenshot from 2019-08-25 14-43-14](https://user-images.githubusercontent.com/19673/63650072-bcc25000-c746-11e9-9058-27e55db7f4fd.png)

Good news is that running Tangram with `WEBKIT_DISABLE_COMPOSITING_MODE=1` fixes the issue. 

Found here https://www.reddit.com/r/gnome/comments/af79nu/laggy_scrolling_in_gnome_webepiphany/edwt32b/

**Comment by sonnyp** [comment]
Should be fixed with https://github.com/sonnyp/Tangram/commit/ea2ddcb7ea0c8d65c36a64f1672519735735b061

Can you try master?

**Comment by codyfish** [comment]
Yes it seems to be fixed, thank you! Keep up the great work!

**Comment by sonnyp** [comment]
I just ran some test with [webkit2gtk-unstable](https://aur.archlinux.org/packages/webkit2gtk-unstable/) on Arch Linux, Reddit and Twitter feel much better.

Release notes for webkitgtk 2.25

* https://webkitgtk.org/2019/05/27/webkitgtk2.25.1-released.html
* https://webkitgtk.org/2019/06/17/webkitgtk2.25.2-released.html
* https://webkitgtk.org/2019/07/23/webkitgtk2.25.3-released.html
* https://webkitgtk.org/2019/08/02/webkitgtk2.25.4-released.html

**Comment by codyfish** [comment]
Can confirm, it feels really smooth now, thank you!
