### ISSUE TITLE
Can't save files

### ISSUE THREAD

**Issue by FakeShemp** [sonnyp/Tangram#52]
Continued from here https://github.com/flathub/re.sonny.Tangram/issues/1

I tried using Tangram for a file hoster service (like Google Drive) but there seem to be no way for the app to save files to local disk, rendering it slightly useless for that purpose.

I would be totally fine with any file download request to just automagically be saved to XDG_DOWNLOAD, no fancy location browser necessary.

Reproduce
* Add https://drive.google.com as an url (and sign in)
* Right click and press `Download` on any file. Nothing will be downloaded

**Comment by sonnyp** [comment]
That is definitely a valid use case :) It's not a flatpak issue, it is just that it's not implemented yet.

Counter suggestion, how about instead I make Tangram open "download" links into applications that can handle the `http(s)://` URI scheme? That would prompt you to open the link in your browser or any application such as download managers that can handle `http(s)://` links.

Would that work for you?

**Comment by FakeShemp** [comment]
Absolutely. That'd be great. Thanks for looking into this.

**Comment by sonnyp** [comment]
@FakeShemp ok, I thought I'd be smarter than anyone by **just** opening the link in the default browser but I forgot about `blob:` and `file:` URIs which are used by applications like [Firefox Send](https://github.com/sonnyp/Tangram/pull/54) for which it's not possible.

So I made https://github.com/sonnyp/Tangram/pull/54

Please tell me what you think.

**Comment by FakeShemp** [comment]
Seems good to me :)

**Comment by sonnyp** [comment]
https://github.com/sonnyp/Tangram/releases/tag/v1.2.0

available on aur and flathub (website might not be up to date yet)
