### ISSUE TITLE
Flatpak identifies required runtime as unused.

### ISSUE THREAD

**Issue by SrStick** [sonnyp/Tangram#53]
![image](https://user-images.githubusercontent.com/28923770/64912182-0547aa80-d702-11e9-8c81-95cf18cfb1fc.png)

<b>OS</b>: Linux Mint 19.2
<b>DE</b>: XFCE

**Comment by sonnyp** [comment]
How is that related with Tangram?

**Comment by SrStick** [comment]
![image](https://user-images.githubusercontent.com/28923770/64913609-88c0c600-d719-11e9-9293-c1f359d78d2e.png)
In my installation flatpak download this dependency. Without it the pages do not load and generates this error:
![image](https://user-images.githubusercontent.com/28923770/64913653-8ca11800-d71a-11e9-9fee-6ae0f0712b9b.png)

**Comment by sonnyp** [comment]
I see. It's not an issue with Tangram though.

Can you check if you can reproduce with the latest flatpak https://launchpad.net/~alexlarsson/+archive/ubuntu/flatpak ?

If so please file an issue https://github.com/flatpak/flatpak

**Comment by SrStick** [comment]
You don't have control over this runtime?

**Comment by sonnyp** [comment]
`org.freedesktop.Platform.GL` is not a direct "dependance" of Tangram

Here is Tangram flatpak manifest on flathub: https://github.com/flathub/re.sonny.Tangram/blob/master/re.sonny.Tangram.json

**Comment by sonnyp** [comment]
@SrStick if you open an issue on flatpak or find a fix can you share here for others?

**Comment by SrStick** [comment]
Ok.

**Comment by sonnyp** [comment]
thanks - we can close this though as it's not a Tangram issue and others will still be able to find it

**Comment by SrStick** [comment]
I updated my version of flatpak and this issue has been resolved
