### ISSUE TITLE
Enable swipe navigation gesture

### ISSUE THREAD

**Issue by Exalm** [sonnyp/Tangram#58]
I think the app should enable swipe gestures webkit provides in addition to the already available pinch zoom. :)

The API: https://webkitgtk.org/reference/webkit2gtk/stable/WebKitSettings.html#webkit-settings-set-enable-back-forward-navigation-gestures

See https://blogs.gnome.org/alexm/2019/09/13/gnome-and-gestures-part-1-webkitgtk/ for more in depth explanation.

**Comment by sonnyp** [comment]
https://github.com/sonnyp/Tangram/releases/tag/v1.2.0

available on aur and flathub (website might not be up to date yet)
