### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by airon90** [sonnyp/Tangram#59]
I know that there are only a few keys but I would like to translate this app into Italian. How could I do that?

**Comment by sonnyp** [comment]
Unfortunately I didn't have the time yet to make Tangram properly translatable but I will do so and let you know! Thanks

**Comment by codyfish** [comment]
I could provide support for German if needed.

**Comment by Vistaus** [comment]
And I will provide the Dutch translation :)

**Comment by dessasin** [comment]
I could provide support for Turkish Language

**Comment by sonnyp** [comment]
Tangram is now translatable. 

https://github.com/sonnyp/Tangram#translation
