### ISSUE TITLE
Netflix and Spotify don't work

### ISSUE THREAD

**Issue by airon90** [sonnyp/Tangram#60]
I suppose it is because of user agent. Is there a way to change it? If so, is it possible to add settings to change it?

**Comment by sonnyp** [comment]
Yes, I would like to add settings to change some properties for each tab like user agent. However Netflix won't work anyway because it requires DRM stuff, not sure about Spotify.

**Comment by gnfpt** [comment]
Hi, 
Maybe you can use widevine (libwidevinecdm.so) the way chromium at_some_point_was/is using it: https://gist.github.com/basrieter/44a463a97a60958c36435d54d50debb4

**Comment by sonnyp** [comment]
User agent can be customized now

However Netflix and Spotify won't work without DRM anyway.

Tangram uses WebkitGTK, not Chromium - more information at https://blogs.igalia.com/xrcalvar/category/planets/planet-webkitgtk/
