### ISSUE TITLE
Spellchecking support

### ISSUE THREAD

**Issue by rafaelmardojai** [sonnyp/Tangram#63]

**Comment by sonnyp** [comment]
https://github.com/sonnyp/Tangram/commit/0126e176bc3961dad1c990dcec317a1fa857204b

can you try and confirm it works fine for you?

**Comment by rafaelmardojai** [comment]
Working nicely, thanks.

**Comment by Foggalong** [comment]
I still don't have notifications as of 1.2.0, not sure it's only in a later release?

**Comment by sonnyp** [comment]
it's not released yet

**Comment by sonnyp** [comment]
v1.3.0 is out with spell checking enabled
