### ISSUE TITLE
Cancel button with icon doesn't look gnomish 

### ISSUE THREAD

**Issue by rafaelmardojai** [sonnyp/Tangram#64]
![Captura de pantalla de 2019-09-23 09-49-05](https://user-images.githubusercontent.com/6210397/65436437-c2639200-dde7-11e9-96af-e335eaf82ec3.png)

**Comment by bertob** [comment]
Usually we just do Cancel without the a back arrow. That would probably be fine here too, no?

**Comment by sonnyp** [comment]
@bertob right, the reason I have an arroiw is because AFAIK Cancel only appears on modal windows

**Comment by sonnyp** [comment]
Back arrow was removed.
