### ISSUE TITLE
Rework "Done" button behavior 

### ISSUE THREAD

**Issue by rafaelmardojai** [sonnyp/Tangram#65]
The "Done" button is confusing. 
It can give the impression that will turn sensible after entering a valid url.

I suggest hiding it completely and showing it when the page has loaded.

**Comment by sonnyp** [comment]
yep you're right

I thought about moving the URL bar to the center of the window with a "Go" button, like a search engine kindof. What do you think?

**Comment by rafaelmardojai** [comment]
yeah, that can work pretty well

**Comment by bertob** [comment]
> I thought about moving the URL bar to the center of the window with a "Go" button, like a search engine kindof. What do you think?

Sounds interesting, worth a try IMO :)

In general, it might be good to give a bit more information during the "add site" flow. If you go this route you could add some copy above the URL entry, e.g. "Type in the URL for the website you want to add."

**Comment by lobau** [comment]
As a simple fix, what do you think of that?  @bertob @sonnyp 
Copying the same style as Epiphany. I am not certain how placeholders changed with the new design, but I assume not much?

![image](https://user-images.githubusercontent.com/6750584/150034676-4cbefdd0-ad82-409b-afa0-d64dd435dbd7.png)

**Comment by lobau** [comment]
Also, maybe changing the string from "Done" to "Add current page" or "Add Page" for example could be helpful

**Comment by sonnyp** [comment]
@lobau thanks for the mockup - I will do this for now :+1: 

I'd like to make Tangram mobile friendly #87 so I'm probably gonna overhaul the UI anyway; we can come up with a more radical solution then.

**Comment by sonnyp** [comment]
Ok I took some time to do something nicer

https://floss.social/@sonny/109654149396391085
