### ISSUE TITLE
Discord's login page freezes

### ISSUE THREAD

**Issue by FakeShemp** [sonnyp/Tangram#67]
When I try to enter in to Discord's login page, the entire page seem to freeze. I can't input text or press buttons.

Seem to only be the login page (https://discordapp.com/login) as the main page seem to work all right.

I'm on Ubuntu 19.04, using the flatpak version.

**Comment by sonnyp** [comment]
Hey,

That's weird, it's super smooth on my computer.
Looks like an upstream bug. Can you reproduce on epiphany/GNOME Web?

**Comment by FakeShemp** [comment]
Actually, yes, I am able to reproduce on epiphany. I'll file a bug over there :)

**Comment by sonnyp** [comment]
Thanks, can you share it here and close this issue when you do so?

**Comment by FakeShemp** [comment]
https://gitlab.gnome.org/GNOME/epiphany/issues/961

**Comment by sonnyp** [comment]
ah sorry, I should have been more precised, issue should be reported on webkitgtk
