### ISSUE TITLE
WhatsApp Web not loading

### ISSUE THREAD

**Issue by codyfish** [sonnyp/Tangram#68]
WhatsApp Web isn't loading its gui. When deleting and recreating the tab, the qr code isn't loaded. 

It works in epiphany. I've noticed this the first time when upgrading to and git version of webkit2gtk. Later the same issue reappeared in the repo version (arch) of webkit2gtk, disappeared again and reappeared with an other update. 

Current version of webkit2gtk: 2.26.1-1

This might be an upstream problem in webkit2gtk, but well it works in epiphany.

**Comment by sonnyp** [comment]
duplicate https://github.com/sonnyp/Tangram/issues/66 ?

**Comment by codyfish** [comment]
Yes, can confirm. Sorry. It takes several minutes to load but eventually it loads.

Thank you for your hard work and always being there for support.
