### ISSUE TITLE
No Notifications

### ISSUE THREAD

**Issue by Foggalong** [sonnyp/Tangram#69]
I don't seem to be receiving any notifications with the following setup:

Tangram: 1.2.0 (Flathub)
OS: Ubuntu 18.04.3
DE: GNOME Shell 3.28.4

Happy to test and provide more details on request!

**Comment by sonnyp** [comment]
Can you try adding https://jhmux.codesandbox.io/ , reloading Tangram and tell me if you can get notifications from there?

**Comment by Foggalong** [comment]
I do get notifications from there! Having done some more testing I appear to be getting notifications from some websites but not others:

Working:
* Telegram
* Gmail
* Google Calendar

Not working:
* Outlook
* Facebook Messenger

Guessing it's something to do then with the permissions for the later category being incorrectly denied?

**Comment by sonnyp** [comment]
I don't know about outlook but on messenger you have to enable desktop notifications in the settings

**Comment by Foggalong** [comment]
I've enabled them in messenger now, will update as to whether that works. For Outlook the notifications were already enabled but don't seem to be coming through

**Comment by sonnyp** [comment]
@Foggalong any news? I'd like to make a new release soon-ish and include a fix if your issue is valid.

**Comment by Foggalong** [comment]
@sonnyp Messenger is now working, Outlook is not

**Comment by sonnyp** [comment]
@Foggalong can you reproduce with GNOME Web or only Tangram?

**Comment by Foggalong** [comment]
That's a good shout, will have a go tomorrow and get back to you!

**Comment by Pobega** [comment]
I'm having the same issue with Hangouts. Messenger works fine when you manually set the notification setting, but Hangouts doesn't seem to work by default with no way to force-toggle desktop notifications to on.

**Comment by sonnyp** [comment]
@Pobega same question, can you reproduce with GNOME Web or only Tangram?

**Comment by Pobega** [comment]
@sonnyp I just tried it with the Epiphany Flatpak (which might or might not be outdated? It's 3.28.3.1) and I was seeing the same behavior there.

**Comment by sonnyp** [comment]
Then I'd suggest to open an issue with https://webkitgtk.org/
