### ISSUE TITLE
high cpu usage WebKitWebProcess with Mattermost

### ISSUE THREAD

**Issue by subjectdenied** [sonnyp/Tangram#7]
i get 65% of cpu usage if a tab with a custom https secured Mattermost open, or maybe with more than one tab open (currently Whatsapp and Mattermost)

**Comment by sonnyp** [comment]
can you reproduce with GNOME Web/epiphany?

**Comment by subjectdenied** [comment]
i just tested this in epiphany on fedora30 with 2 tabs (whatsapp, mattermost) open, and get like 4% cpu usage, while doing the same with gigagram 64% of cpu-usage is shown for WebKitWebProcess

btw thanks, this application is amazing, i so would like to get rid of electron for this use-case

**Comment by sonnyp** [comment]
I could not reproduce

Tested with

```sh
wget https://github.com/sonnyp/gigagram/releases/download/v0.3.0/gigagram.flatpak
flatpak install --user gigagram.flatpak
```

and 2 tabs; (`demo.mattermost.com` and `web.whatsapp.com`) on Arch/GNOME Shell/Wayland

Questions:

Can you see if you can reproduce with `demo.mattermost.com` ?

Do you get high CPU usage immediately or after a while?

Can you try to reproduce with non flatpak version:

```
git clone git@github.com:sonnyp/gigagram.git
cd gigagram
make build
./install/bin/re.sonny.gigagram
```

**Comment by subjectdenied** [comment]
for some reason this seems to work now flawlessly, it may have been an issue with fedora rawhide and the webkitgtk shipped with it, which i now replaced with fedora 30
