### ISSUE TITLE
Session is dropped on Tangram close

### ISSUE THREAD

**Issue by miloskroulik** [sonnyp/Tangram#70]
It seems that Tangram drops cookies on browser close. I tried to use it to access a Redmine installation. In my usual browser (Vivaldi), I'm still logged in after next browser startup, while in Tangram I'm logged out. Is there any solution for that?

**Comment by sonnyp** [comment]
Can you reproduce in Gnome Web ?

Otherwise please close tangram and share the output of

```sh
flatpak --version
flatpak run re.sonny.Tangram
```
