### ISSUE TITLE
Copy/paste is not working in microsoft teams

### ISSUE THREAD

**Issue by plooff** [sonnyp/Tangram#72]
As the title says, copy/paste is not working in [microsoft teams](https://teams.microsoft.com/) (the microsoft version of slack)
I cannot reproduce the bug in Epiphany because the website says that this browser is not supported (I don't know if I can change the user-agent in epiphany)

**Tangram version**

Tangram : 1.2.0
WebKitGTK : 2.26.2
gjs : 1.58.1

**Linux distribution**

Archlinux

**Flatpak version**

I'm using the AUR version (which is built from the source I think) not the flatpak one

**Desktop environment**

Gnome 3.34.1 Wayland

**Comment by sonnyp** [comment]
> I don't know if I can change the user-agent in epiphany

Can you try ?

https://askubuntu.com/questions/472861/how-to-change-the-user-agent-in-gnome-web-epiphany

**Comment by lebr** [comment]
It works !
Thank you.

**Comment by sonnyp** [comment]
v1.3.0 is out with customizable per tab user agent
