### ISSUE TITLE
WhatsApp very slow or not connecting

### ISSUE THREAD

**Issue by rafwes** [sonnyp/Tangram#74]
Hello!

I am facing problems opening WhatsApp Web and keeping the session alive. On first open it will take a long time to show the QR code. Sometimes it will plainly fail. When it does not, you can login, but if I close and open the app, it will have a hard time reconnecting. 

Thanks for looking it up.

**Comment by sonnyp** [comment]
https://github.com/sonnyp/Tangram#reporting-an-issue

**Comment by rafwes** [comment]
Thanks, Found the bug here https://bugs.webkit.org/show_bug.cgi?id=203404
