### ISSUE TITLE
New Icon Colors

### ISSUE THREAD

**Issue by bertob** [sonnyp/Tangram#76]
A while back we discussed changing the icon colors, I finally got around to trying a few new variations:

![image](https://user-images.githubusercontent.com/1908896/77800520-3cb2ee80-7077-11ea-8fd7-30caa864a01c.png)

![image](https://user-images.githubusercontent.com/1908896/77800583-61a76180-7077-11ea-8866-9913de47ba4d.png)

![image](https://user-images.githubusercontent.com/1908896/77800611-7552c800-7077-11ea-9b2e-765b66f28ee4.png)

Let me know if there's anything here you like :)

**Comment by sonnyp** [comment]
hey @bertob , thanks a lot

I think the palettes work quite well but I'm having a really hard time liking any of them. Maybe because I'm so used to the current one.

Do you have a personal preference? Do you think any of them is *better* than the current one or is it more about not using "official" GNOME colours?

**Comment by bertob** [comment]
I think the main conerns we had when we last discussed this were
1. A few geometric shapes in GNOME colors aren't much of an identity. More custom colors would help this app have a more recognizable brand.
2. The saturated primary colors make it feel a bit like a Google product.

Among the three options in the issue I think the first is the strongest personally, but all three would accomplish the two goals we had. If you're not fully convinced we can try a few more color variants though.

**Comment by digitalethics** [comment]
I agree that the first one is the strongest. Overall it feels much fresher and recognizable. FWIW I've never used Tangram before and I would feel most comfortable with this one. The current one is too Google-esque.

**Comment by sonnyp** [comment]
@bertob could you share the source for the first one ? 

Out of curiosity, did you try this version (with a border) and all pieces of the same colour?

**Comment by bertob** [comment]
Yeah, but it looks pretty boring:

![image](https://user-images.githubusercontent.com/1908896/87233495-46fbbd00-c3c8-11ea-8375-8db61f84f075.png)

Here's the source: [re.sonny.Tangram.Source.zip](https://github.com/sonnyp/Tangram/files/4907574/re.sonny.Tangram.Source.zip)

**Comment by sonnyp** [comment]
https://github.com/sonnyp/Tangram/commit/09bd01d6bb17afeb08fde71ab9a8cacb85e3184e

**Comment by sonnyp** [comment]
@bertob thank you. Icon updated with the first version.

**Comment by bertob** [comment]
Thanks!
