### ISSUE TITLE
WebKitGTK & Outlook Incompatiblity

### ISSUE THREAD

**Issue by Foggalong** [sonnyp/Tangram#80]
Just wanted to flag that through no fault of yours I don't think I'll be able to keep using Tangram.

It's still the best app of its kind I've tried but WebKitGTK has started to cause issues with some of the websites I use. Most of these were minor things but the biggie is that it's no longer capable of loading full featured Outlook. Instead loads a light version which is missing some key features like email archiving and keyboard shortcuts. I was going to file an upstream issue but they seem to want me to create an account just for their Bugzilla which I'm not willing to do, so thought I'd flag it to you here so that you're at least aware of it and can file if you want to.

Thanks for the work you've put into this, it's really much appreciated!

**Comment by sonnyp** [comment]
>  it's no longer capable of loading full featured Outlook

You've got this the other way around. It is Microsoft who decides when/where to load the light version. I would suggest sending a complaint to them.

Tangram 1.3.0 (not yet release) supports switching user agent which might help working around this issue.
