### ISSUE TITLE
Option to remove white screens

### ISSUE THREAD

**Issue by retesta** [sonnyp/Tangram#81]
Would it be possible to have an option to replace the white screens in the app with gray/dark ones instead? 
Every time I open the application or add a new container at night (most of my usage) I am blinded by a bright white screen.

**Comment by sonnyp** [comment]
Are you using some kind of GTK dark theme or dark mode?

**Comment by retesta** [comment]
Yes, I am using the Zorin Dark GTK theme "ZorinGreen-Dark"

**Comment by sonnyp** [comment]
Implemented in https://github.com/sonnyp/Tangram/pull/84

Was also bothering me :)

Implemented the same way Epiphany does.

Will close this when released.

**Comment by retesta** [comment]
Awesome man, thanks!

**Comment by sonnyp** [comment]
Fixed in v1.3.0
