### ISSUE TITLE
Separate proxy config for each site

### ISSUE THREAD

**Issue by jurek4321** [sonnyp/Tangram#82]
Is it possible to add option to set different user agent and proxy settings for each site?

**Comment by sonnyp** [comment]
It should be fairly easy to do.

We have a WebKit context and WebKit webview per site.

We would need a dialog window to configure each site and implement a UI controlling various WebkitGTK options.

[User agent](https://gjs-docs.gnome.org/webkit240~4.0_api/webkit2.settings#property-user_agent)
[proxy](https://gjs-docs.gnome.org/webkit240~4.0_api/webkit2.webcontext#method-set_network_proxy_settings)

**Comment by sonnyp** [comment]
Would you like to give it a try?

In fact we already have a dialog for each site, https://github.com/sonnyp/Tangram/blob/master/src/instanceDialog.js

I could also implement user agent as an example and anyone could expand from there.

**Comment by sonnyp** [comment]
https://github.com/sonnyp/Tangram/pull/83

**Comment by sonnyp** [comment]
I'll close for now

If anyone is interested in this and can provide a use case I'm happy to reconsider.
