### ISSUE TITLE
Outlook shows the old OWA website

### ISSUE THREAD

**Issue by amolenaar** [sonnyp/Tangram#88]
Please include (to the best of your knowledge) the following information:

**Tangram version**

`1.2.0`

**Linux distribution**

`Ubuntu 20.20`

**Flatpak version**

`Flatpak 1.6.5`

**Desktop environment**

GNOME Shell 3.36.4 on Wayland

**Current behavior**

When I log in to a Microsoft Outlook account on Tangram, the site degrades to the old "OWA" environment. 

![image](https://user-images.githubusercontent.com/96249/92871513-4d78d600-f405-11ea-844c-773d7598e21e.png)

**Expected Behavior**

I expect the new Office365 web environment, which is much more user friendly.

**Comment by sonnyp** [comment]
Same issue on GNOME Web.

This is a Microsoft "bug", consider reporting the issue to Outlook support please.

You can workaround it by setting the user agent of the tab to desktop Safari (for example) `Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.2 Safari/605.1.15`

**Comment by amolenaar** [comment]
Hi @sonnyp, 

Thanks for the update. 

Calender works now, and I can also add attachments to an e-mail.

You did an excellent job!
