### ISSUE TITLE
Slack web sockets aren't working

### ISSUE THREAD

**Issue by mmstick** [sonnyp/Tangram#89]
Please include (to the best of your knowledge) the following information:

**Tangram version**: Flatpak 1.2.0
**Linux distribution**: Pop!_OS 20.04
**Flatpak version**: 1.6.5
**Desktop environment**: GNOME Shell 3.36 X11

Slack has a constant "Last updated <1 minutes ago... Load new messages" message, which happens when web socket connections aren't working.

**Comment by sonnyp** [comment]
Can you reproduce in GNOME Web / epiphany? If, so I'd suggest opening a ticket on http://webkitgtk.org/

**Comment by sonnyp** [comment]
I could reproduce with epiphany, looks like a WebKitGTK issue.

**Comment by philn** [comment]
Fix: https://trac.webkit.org/changeset/267620/webkit will be shipped in 2.30.2.

**Comment by sonnyp** [comment]
fixed in Tangram 1.3.1
