### ISSUE TITLE
Wire web browser unsupported (user agent changes required)

### ISSUE THREAD

**Issue by mmstick** [sonnyp/Tangram#90]
Please include (to the best of your knowledge) the following information:

Tangram version: Flatpak 1.2.0
Linux distribution: Pop!_OS 20.04
Flatpak version: 1.6.5
Desktop environment: GNOME Shell 3.36 X11

https://app.wire.com claims that the web browser is unsupported. The ability to change user agents should fix it.

**Comment by sonnyp** [comment]
v1.3.0 is out with customizable per tab user agent
