### ISSUE TITLE
Problems Logging Into Google Drive and Google Docs

### ISSUE THREAD

**Issue by aaylnx** [sonnyp/Tangram#91]
I'm just trying out Tangram. Very nice! I am able to access Gmail and Google Calendar with no problems.

However, when I try to access Google Drive it redirects me to my desktop default browser (Brave) rather than allowing me to log in directly through Tangram.

When I try to log into Google Docs it takes me to the authentication page without any problems, but after I put in my user name and password it just goes to a blank screen. It never successfully logs in.

Any suggestions?

**Comment by sonnyp** [comment]
> I'm just trying out Tangram. Very nice! 

Thank you :smiley: 


> when I try to access Google Drive it redirects me to my desktop default browser (Brave) rather than allowing me to log in directly through Tangram.

Looks like https://github.com/sonnyp/Tangram/issues/85 

> When I try to log into Google Docs it takes me to the authentication page without any problems, but after I put in my user name and password it just goes to a blank screen. It never successfully logs in.

Can you reproduce with GNOME Web?

**Comment by aaylnx** [comment]
Thank you for the reply. I just installed Gnome Web via flatpak and I am able to log into Google Drive with it without any problems.

In Tangram, when I go to https://www.google.com/intl/en/drive/, if I click on "Go To Drive", it redirects to my default desktop browser, Brave. I'm not sure if this matters, but I'm using Kubuntu 20.04. I even tried to make Tangram the default browser in the KDE settings, but it still redirects to Brave. 

Again, it works fine when I sign into to Gmail and Google Calendar. 

Unlike before, I also find that I am now able to log into Google Docs, but not Google Drive.

**Comment by sonnyp** [comment]
Thanks - I had a look and understand the issue better now.

https://github.com/sonnyp/Tangram/pull/104 request for comments
