### ISSUE TITLE
Unable to log into Google Drive or Google Docs

### ISSUE THREAD

**Issue by aaylnx** [sonnyp/Tangram#92]
I'm just trying out Tangram. Very nice! I am able to access Gmail and Google Calendar with no problems.

However, when I try to access Google Drive it redirects me to my desktop default browser (Brave) rather than allowing me to log in directly through Tangram.

When I try to log into Google Docs it takes me to the authentication page without any problems, but after I put in my user name and password it just goes to a blank screen. It never successfully logs in.

Any suggestions?

**Comment by sonnyp** [comment]
@aaylnx did you find a solution? maybe you can share for others?
