### ISSUE TITLE
Possible Conversion to TypeScript

### ISSUE THREAD

**Issue by mmstick** [sonnyp/Tangram#93]
If there's interest in this, I have experience with using TypeScript to generate JavaScript for GJS. Tends to catch most logic errors on the spot, and makes dealing with the GNOME API much easier when you have precise type information to work with.

**Comment by sonnyp** [comment]
If Tangram gets a rewrite - it will be in C to benefit from the work that goes into Epiphany.

I might add a jsconfig with types thought similar to https://github.com/sonnyp/Workbench/commit/d9446d481715f601faa811a5bfe83f195e2284a5

**Comment by mmstick** [comment]
🤢🤮

**Comment by sonnyp** [comment]
:hankey: 

---

Make sure you don't open any issue or interact in any way with this repository again. https://github.com/sonnyp/Tangram/issues?q=is%3Aissue+author%3Ammstick+is%3Aclosed
