### ISSUE TITLE
Window Title Should Change With Active Tab

### ISSUE THREAD

**Issue by mmstick** [sonnyp/Tangram#94]
Just like web browsers do it

**Comment by sonnyp** [comment]
Will conflict with https://github.com/sonnyp/Tangram/issues/21

**Comment by sonnyp** [comment]
Actually no it wouldn't.

I'm not strongly opposed to this but can you explain why?

**Comment by mmstick** [comment]
Can you guess which web app that is active in Tangram from the stack?

![Screenshot from 2020-09-11 22-44-38](https://user-images.githubusercontent.com/4143535/92987528-768a7c80-f480-11ea-9c55-ee8e2b418c67.png)

**Comment by sonnyp** [comment]
@mmstick why do you need to know which web app is active when Tangram in the background?

Unrelated by I need to fix that title, it should be `Tangram` not `re.sonny.Tangram`

**Comment by sonnyp** [comment]
It's still unclear to me how the suggested change would be helpful.

**Comment by mmstick** [comment]
Just because you don't see why it would be helpful doesn't mean that it isn't useful to have implemented to have. Say that I'm monitoring cryptocurrency prices, and rather than having a window visible at all times, I just want to see the title of the table in a stack. I can do that with Firefox and Chrome. Can't do that with Tangram.

**Comment by sonnyp** [comment]
> Just because you don't see why it would be helpful doesn't mean that it isn't useful to have implemented.

Agree, that's why I asked 

> Say that I'm monitoring cryptocurrency prices, and rather than having a window visible at all times, I just want to see the title of the table in a stack. I can do that with Firefox and Chrome. Can't do that with Tangram.

Okay, I see.
Personally I'd rather not let title changes be a source of distraction.

It could be an optional parameter in Tangram though. We don't have a settings window yet but that should be fairly easy.

Would you like to give it a try? Happy to help if needed https://github.com/sonnyp/Tangram#development
