### ISSUE TITLE
Standalone Web App Mode

### ISSUE THREAD

**Issue by mmstick** [sonnyp/Tangram#95]
For the times you want a web app without a headerbar, tabs, and other web browser controls in the way.

**Comment by sonnyp** [comment]
Any specific reason why not using https://fedoramagazine.org/standalone-web-applications-gnome-web/ ?

**Comment by mmstick** [comment]
I don't use GNOME Web, or have it installed.

**Comment by sonnyp** [comment]
https://github.com/sonnyp/Tangram/issues/21 will allow this (as a side effect)

But honestly, GNOME Web or https://github.com/peppermintos/ice would do a better job at this.
