### ISSUE TITLE
gitlab.gnome.org

### ISSUE THREAD

**Issue by TheEvilSkeleton** [sonnyp/Tangram#97]
Hello, just wondering, since the project is mostly focused on GNOME, why not host the code on https://gitlab.gnome.org/ instead?

**Comment by sonnyp** [comment]
:wave: 

I think it would be easier to answer / act upon if you explain why you think it should be hosted on https://gitlab.gnome.org

**Comment by TheEvilSkeleton** [comment]
That is because the GNOME forge has a group specifically for the community: https://gitlab.gnome.org/World.

The community helps a lot with GTK/GNOME projects, as seen here (https://gitlab.gnome.org/groups/World/-/issues).

Even Lollypop for example is hosted there: https://gitlab.gnome.org/World/lollypop.

**Comment by sonnyp** [comment]
From https://gitlab.gnome.org/World

> Non official GNOME projects that use additional GitLab functionality (e.g. CI).
>
> Read the requirements if you want a project to be part of it.

Link to requirements is broken.

**Comment by TheEvilSkeleton** [comment]
That was unexpected. I'll try to find the repo I can open an issue in.

**Comment by TheEvilSkeleton** [comment]
Looks like they have fixed it. Here's the new link: https://wiki.gnome.org/Projects/Prerequisites

**Comment by sonnyp** [comment]
Thanks.

I don't see the benefit of moving the project to gitlab.gnome.org
Nothing prevents the community from helping on GitHub, and they have.

Might reconsider in the future but not interested spending time on this at the moment.
