### ISSUE TITLE
How to activate dark mode?

### ISSUE THREAD

**Issue by aaylnx** [sonnyp/Tangram#98]
Is there a way to enable dark mode in Tangram? I see that the changelog for 1.3 says "New tab background color respects dark mode", but I'm not quite sure what that means. Some sites, like WhatsApp for example, have a dark mode I can turn on in the settings. Others, I'm particularly thinking of Google Calendar, Contacts, and Voice, have no such option. In the browser, I'm able to use the "Dark Reader" extension to take care of this, but I'm not sure whether there's a way to do this in Tangram or not. Thanks!

**Comment by sonnyp** [comment]
Dark mode is only for the new tab. Individual websites have to implement dark mode themselves.
